---

- name: Install AWS CLI
  pip:
    name: awscli
  become: true

- name: Put mysql backup in S3
  command: "aws s3 cp --quiet {{ BACKUP_LOCATION }}/{{ BACKUP_DATE }}_mysql.tar.gz s3://{{ AWS_S3_DBS_BACKUP_BUCKET_NAME }}/ --host {{ AWS_S3_DBS_BACKUP_HOST }} --host-bucket {{ AWS_S3_DBS_BACKUP_BUCKET_NAME }}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ EDXAPP_BACKUPS_AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ EDXAPP_BACKUPS_AWS_SECRET_ACCESS_KEY }}"
  when: backup_mysql

- name: Put mongo backup in S3
  command: "aws s3 cp --quiet {{ BACKUP_LOCATION }}/{{ BACKUP_DATE }}_mongo.tar.gz s3://{{ AWS_S3_DBS_BACKUP_BUCKET_NAME }}/ --host {{ AWS_S3_DBS_BACKUP_HOST }} --host-bucket {{ AWS_S3_DBS_BACKUP_BUCKET_NAME }}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ EDXAPP_BACKUPS_AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ EDXAPP_BACKUPS_AWS_SECRET_ACCESS_KEY }}"
  when: backup_mongo
