---

richie_elasticsearch_containers:
  elasticsearch_1:
    data: /data/richie/elasticsearch_1/
    host_fqdn: "{{ richie_elasticsearch_1_server }}"    
  elasticsearch_2:
    data: /data/richie/elasticsearch_2/
    host_fqdn: "{{ richie_elasticsearch_2_server }}"
  elasticsearch_3:
    data: /data/richie/elasticsearch_3/
    host_fqdn: "{{ richie_elasticsearch_3_server }}"


richie_elasticsearch_docker_deploy_folders_additional:
  - dest: /data/richie/elasticsearch_1/
    dir_owner: 1000
    dir_group: 1000
    dir_mode: "0755"
    when: "{{ inventory_hostname == richie_elasticsearch_1_server }}"
  - dest: /data/richie/elasticsearch_2/
    dir_owner: 1000
    dir_group: 1000
    dir_mode: "0755"
    when: "{{ inventory_hostname == richie_elasticsearch_2_server }}"
  - dest: /data/richie/elasticsearch_3/
    dir_owner: 1000
    dir_group: 1000
    dir_mode: "0755"
    when: "{{ inventory_hostname == richie_elasticsearch_3_server }}"

richie_elasticsearch_cluster_initial_master_nodes: "{{ richie_elasticsearch_containers.keys() | list | join(',') }}"

richie_elasticsearch_1_server: !!null
richie_elasticsearch_2_server: !!null
richie_elasticsearch_3_server: !!null

richie_sysctl_conf:
  vm.max_map_count: 262144
