---
richie_mysql_containers:
  mysql_1:
    hostname: "{{ richie_mysql_1_hostname }}"
    data: /data/richie/mysql_1/
    host_fqdn: "{{ richie_mysql_primary_server }}"
    ingress_port: 24308
    primary: True
    mysql_replication_login_user: root
    mysql_replication_login_password: "{{ richie_MYSQL_ROOT_PASSWORD }}"
    mysql_replication_login_port: 24308
    docker_config_name_mysql_cfg: mysql_1_cfg
    docker_secret_name_mysql_root_password: mysql_1_root_password
    server_id: 1
    mysql_replication_slave_server_ip: "%"
    mysql_replication_user: "{{ richie_mysql_replication_user }}"
    mysql_replication_password: "{{ richie_mysql_replication_password }}"
    mysql_replication_init_databases: [ "{{ richie_nau_MYSQL_DATABASE }}" ]
  mysql_2:
    hostname: "{{ richie_mysql_2_hostname }}"
    data: /data/richie/mysql_2/
    host_fqdn: "{{ richie_mysql_replica_server }}"
    ingress_port: 24309
    primary: False
    mysql_replication_login_user: root
    mysql_replication_login_password: "{{ richie_MYSQL_ROOT_PASSWORD }}"
    mysql_replication_login_port: 24309
    docker_config_name_mysql_cfg: mysql_2_cfg
    docker_secret_name_mysql_root_password: mysql_2_root_password
    server_id: 2
    read_only: True
    mysql_replication_master_server_ip: "{{ richie_mysql_1_hostname }}"
    mysql_replication_master_port: 3306
    mysql_replication_user: "{{ richie_mysql_replication_user }}"
    mysql_replication_password: "{{ richie_mysql_replication_password }}"

richie_mysql_docker_deploy_templates:
  - src_data: "{{ richie_MYSQL_ROOT_PASSWORD }}"
    dest: "{{ docker_deploy_base_folder }}/mysql_1/mysql-root-password"
    secret_name: "{{ richie_mysql_containers.mysql_1.docker_secret_name_mysql_root_password }}"
    service: mysql_1
    docker_target: /run/secrets/mysql-root-password
  - src_data: "{{ richie_MYSQL_ROOT_PASSWORD }}"
    dest: "{{ docker_deploy_base_folder }}/mysql_2/mysql-root-password"
    secret_name: "{{ richie_mysql_containers.mysql_2.docker_secret_name_mysql_root_password }}"
    service: mysql_2
    docker_target: /run/secrets/mysql-root-password
  - src:  roles/docker_mysql_replication/templates/replication.cnf.j2
    dest: "{{ docker_deploy_base_folder }}/mysql_1/mysql.cfg"
    config_name: "{{ richie_mysql_containers.mysql_1.docker_config_name_mysql_cfg }}"
    mysql_container: "{{ richie_mysql_containers.mysql_1 }}"
    service: mysql_1
    docker_target: /etc/mysql/conf.d/mysql.cnf
  - src:  roles/docker_mysql_replication/templates/replication.cnf.j2
    dest: "{{ docker_deploy_base_folder }}/mysql_2/mysql.cfg"
    config_name: "{{ richie_mysql_containers.mysql_2.docker_config_name_mysql_cfg }}"
    mysql_container: "{{ richie_mysql_containers.mysql_2 }}"
    service: mysql_2
    docker_target: /etc/mysql/conf.d/mysql.cnf
  - src:  templates/load_balancer_haproxy/haproxy.cfg
    dest: "{{ docker_deploy_base_folder }}/load_balancer_haproxy/haproxy.cfg"
    config_name: richie_mysql_haproxy_cfg
    service: load_balancer_haproxy
    docker_target: /usr/local/etc/haproxy/haproxy.cfg

richie_mysql_1_hostname: "{{ richie_docker_deploy_stack_name }}_mysql_1"
richie_mysql_2_hostname: "{{ richie_docker_deploy_stack_name }}_mysql_2"

# Folders that need to be created on each docker swarm node
richie_mysql_docker_deploy_folders_additional:
  - dest: /data/richie/mysql_1/
    dir_owner: 999
    dir_group: root
    dir_mode: "0755"
    when: "{{ inventory_hostname == richie_mysql_primary_server }}"
  - dest: /data/richie/mysql_2/
    dir_owner: 999
    dir_group: root
    dir_mode: "0755"
    when: "{{ inventory_hostname == richie_mysql_replica_server }}"

# MySQL Database configuration
richie_nau_MYSQL_DATABASE: richie_nau
richie_nau_MYSQL_USER: richie_nau
richie_mysql_replication_user: richie_replication
# richie_mysql_replication_password:

# Used by docker_mysql_replication role
richie_docker_mysql_replication_additional_databases:
  # one per site
  - "{{ richie_nau_MYSQL_DATABASE | default(None) }}"

richie_docker_mysql_replication_additional_users:
  # one per site
  - {
      db: "{{ richie_nau_MYSQL_DATABASE | default(None) }}",
      user: "{{ richie_nau_MYSQL_USER | default(None) }}",
      pass: "{{ richie_nau_app_richie_MYSQL_PASSWORD | default(None) }}",
      host: "%"
    }
  - {
      db: "*",
      user: "{{ openark_orchestrator_client_user | default(None) }}",
      pass: "{{ openark_orchestrator_client_password | default(None) }}",
      host: "{{ openark_orchestrator_client_mysql_host }}",
      # ndbinfo.processes:SELECT
      priv: "*.*:SUPER,PROCESS,REPLICATION SLAVE,REPLICATION CLIENT,RELOAD/meta.*:SELECT/performance_schema.replication_group_members:SELECT"
    }
  - {
      db: "*",
      user: "{{ richie_load_balancer_haproxy_health_check_user }}",
      host: "{{ richie_load_balancer_haproxy_health_check_host | default('%') }}",
    }

richie_mysql_primary: "{{ richie_mysql_containers.values() | list | selectattr('primary', 'equalto', True) | first }}"
