---
#
# Redis configurations
#
richie_redis_docker_image: docker.io/bitnami/redis:6.2.7-debian-11-r49

richie_redis_containers:
  redis_1:
    host_fqdn: "{{ richie_redis_1_server }}"
    mode: master
    dest: /data/richie/redis_1/
    dir_owner: 1001
    dir_group: 1001
    dir_mode: "0755"
    when: "{{ inventory_hostname == richie_redis_1_server }}"
  redis_2:
    host_fqdn: "{{ richie_redis_2_server }}"
    mode: master
    dest: /data/richie/redis_2/
    dir_owner: 1001
    dir_group: 1001
    dir_mode: "0755"
    when: "{{ inventory_hostname == richie_redis_2_server }}"

richie_redis_docker_deploy_folders_additional: "{{ richie_redis_containers.values() | list }}"

richie_redis_1_server: !!null
richie_redis_2_server: !!null
