---

nginx_default_site_template_title: "Default page"
nginx_default_site_template_body_text: "Change me"
nginx_default_site_port: 8080
nginx_default_site_ssl_port: 4043
nginx_default_site_ssl_certificate: !!null
nginx_default_site_certificate_key: !!null
nginx_default_site_templates_root: "/var/www/nau"

nginx_default_site_use_https: false
