---
- name: Run healthcheck
  shell: make status-healthcheck
  args:
    chdir: "{{ staticproxy_docker_deploy_base_folder }}"
  retries: "{{ docker_deploy_stack_verify_retries | default(3) }}"
  delay: "{{ docker_deploy_stack_verify_delay | default(15) }}"
  register: result
  until: result.rc == 0
  # run it only when deploying or when on healthcheck mode.
  when: not ansible_check_mode and ( (staticproxy_deploy | default(false)) or (healthcheck | default(false)) )
  changed_when: False
  tags: 
    - healthcheck
