---
# Need to define this variable:
# observability_fluentbit_aggregator_host_fqdn: some-node

# Remove old containers that this stack no longer use
observability_docker_deploy_stack_prune: true

observability_docker_deploy_stack_name: observability
observability_docker_deploy_stack_template: templates/docker-stack.yml
observability_docker_deploy_base_folder: /nau/ops/observability

observability_docker_deploy_templates:
  - src: "{{ observability_makefile_template | default('templates/Makefile') }}"
    dest: "{{ observability_docker_deploy_base_folder }}/Makefile"
  # aggregator
  - src: templates/fluent-bit-aggregator.conf
    dest: "{{ observability_docker_deploy_base_folder }}/fluent-bit-aggregator.conf"
    docker_target: /fluent-bit/etc/fluent-bit.conf
    config_name: fluent_bit_aggregator_conf
    service: fluentbit-aggregator
  - src: templates/extra-parsers.conf
    dest: "{{ observability_docker_deploy_base_folder }}/extra-parsers.conf"
    docker_target: /fluent-bit/etc/extra-parsers.conf
    config_name: extra_parsers_conf
    service: fluentbit-aggregator
  - src: templates/stream_processor.conf
    dest: "{{ observability_docker_deploy_base_folder }}/stream_processor.conf"
    docker_target: /fluent-bit/etc/stream_processor.conf
    config_name: stream_processor_conf
    service: fluentbit-aggregator
  # relay
  - src: templates/fluent-bit-relay.conf
    dest: "{{ observability_docker_deploy_base_folder }}/fluent-bit-relay.conf"
    docker_target: /fluent-bit/etc/fluent-bit.conf
    config_name: fluent_bit_relay_conf
    service: fluentbit-relay

observability_docker_deploy_folders_additional:
  - dest: "{{ observability_fluentbit_aggregator_data }}"
    dir_owner: 999
    dir_group: root
    dir_mode: "0755"
    when: "{{ inventory_hostname == observability_fluentbit_aggregator_host_fqdn }}"
  - dest: "{{ observability_fluentbit_relay_data }}"
    dir_owner: 999
    dir_group: root
    dir_mode: "0755"
    # We don't define `when`, because we really want to create this folder on all the docker nodes
    # This container is defined on `global` mode.

observability_fluentbit_docker_image: fluent/fluent-bit:1.9.8-debug
# image: fluent/fluent-bit:latest-debug
# image: fluent/fluent-bit:latest

# By convention we use /data/<stack name>/<container>
# that is why we have a strange double fluentbit value.
observability_fluentbit_relay_data: /data/observability/fluentbit-relay/
observability_fluentbit_aggregator_data: /data/observability/fluentbit-aggregator/

observability_fluentbit_relay_forward_port: 24224
observability_fluentbit_aggregator_forward_port: 24224

observability_fluentbit_relay_http_port: 2020
observability_fluentbit_aggregator_http_port: 2021

observability_fluentbit_output_docker_service_s3:
  - coursecertificate_nginx
  - staticproxy_nginx
  - richie_nau_nginx
  - openedx_nginx
  # - openedx_lms
  # - openedx_cms
