---
# Need to define this variable:
# observability_fluentbit_aggregator_host_fqdn: some-node

# Remove old containers that this stack no longer use
observability_docker_deploy_stack_prune: true

# Variable to enable or disable the use of debug information, like increase logging verbosity and
# to use the debug fluentbit docker image.
observability_fluentbit_debug: true
observability_fluentbit_log_level: "{{ 'debug' if (observability_fluentbit_debug|bool) else 'info' }}"

observability_docker_deploy_stack_name: observability
observability_docker_deploy_stack_template: templates/docker-stack.yml
observability_docker_deploy_base_folder: /nau/ops/observability

observability_aggregator_node_templates:
  - src: "{{ observability_makefile_template | default('templates/Makefile') }}"
    dest: "{{ observability_docker_deploy_base_folder }}/Makefile"
    when: "{{ inventory_hostname == observability_fluentbit_aggregator_host_fqdn }}"
  - src: "{{ observability_makefile_template | default('makefile-metrics.mk') }}"
    dest: "{{ observability_docker_deploy_base_folder }}/makefile-metrics.mk"
    when: "{{ inventory_hostname == observability_fluentbit_aggregator_host_fqdn }}"
  
observability_docker_deploy_templates:
  - src: "{{ observability_makefile_template | default('templates/Makefile') }}"
    dest: "{{ observability_docker_deploy_base_folder }}/Makefile"
  - src: "{{ observability_makefile_template | default('templates/makefile-base.mk') }}"
    dest: "{{ observability_docker_deploy_base_folder }}/makefile-base.mk"
  - src: "{{ observability_makefile_template | default('templates/makefile-specific.mk') }}"
    dest: "{{ observability_docker_deploy_base_folder }}/makefile-specific.mk"
  # aggregator
  - src: templates/fluent-bit-aggregator.conf
    dest: "{{ observability_docker_deploy_base_folder }}/fluent-bit-aggregator.conf"
    docker_target: /fluent-bit/etc/fluent-bit.conf
    config_name: fluent_bit_aggregator_conf
    service: fluentbit-aggregator
  - src: templates/extra-parsers.conf
    dest: "{{ observability_docker_deploy_base_folder }}/extra-parsers.conf"
    docker_target: /fluent-bit/etc/extra-parsers.conf
    config_name: extra_parsers_conf
    service: fluentbit-aggregator
  - src: templates/stream_processor.conf
    dest: "{{ observability_docker_deploy_base_folder }}/stream_processor.conf"
    docker_target: /fluent-bit/etc/stream_processor.conf
    config_name: stream_processor_conf
    service: fluentbit-aggregator
  # relay
  - src: templates/fluent-bit-relay.conf
    dest: "{{ observability_docker_deploy_base_folder }}/fluent-bit-relay.conf"
    docker_target: /fluent-bit/etc/fluent-bit.conf
    config_name: fluent_bit_relay_conf
    service: fluentbit-relay

observability_docker_deploy_folders_additional:
  - dest: "{{ observability_fluentbit_aggregator_data }}"
    dir_owner: 999
    dir_group: root
    dir_mode: "0755"
    when: "{{ inventory_hostname == observability_fluentbit_aggregator_host_fqdn }}"
  - dest: "{{ observability_fluentbit_relay_data }}"
    dir_owner: 999
    dir_group: root
    dir_mode: "0755"
    # We don't define `when`, because we really want to create this folder on all the docker nodes
    # This container is defined on `global` mode.

observability_fluentbit_docker_image: fluent/fluent-bit:2.0.8{{ '-debug' if (observability_fluentbit_debug|bool) else '' }}

# By convention we use /data/<stack name>/<container>
# that is why we have a strange double fluentbit value.
observability_fluentbit_relay_data: /data/observability/fluentbit-relay/
observability_fluentbit_aggregator_data: /data/observability/fluentbit-aggregator/

observability_fluentbit_relay_forward_port: 24224
observability_fluentbit_aggregator_forward_port: 24224

observability_fluentbit_relay_http_port: 2020
observability_fluentbit_aggregator_http_port: 2021

observability_fluentbit_output_docker_service_s3:
  - coursecertificate_nginx
  - staticproxy_nginx
  - richie_nau_nginx
  - openedx_nginx
  - openedx_lms
  - openedx_lms-worker
  - openedx_cms
  - openedx_cms-worker

observability_fluentbit_metrics: "{{ observability_fluentbit_metrics_functions + observability_fluentbit_metrics_total }}"

observability_fluentbit_metrics_functions:
  - metrics.requests.last5m.time.max
  - metrics.requests.last5m.time.avg

observability_fluentbit_metrics_total:
  - metrics.log.last5m.count.total
  - metrics.requests.last5m.count.total
  - metrics.requests.last5m.code.1xx
  - metrics.requests.last5m.code.2xx
  - metrics.requests.last5m.code.3xx
  - metrics.requests.last5m.code.4xx
  - metrics.requests.last5m.code.5xx

observability_docker_deploy_stack_verify_retries: 120
observability_docker_deploy_stack_verify_delay: 60

observability_fluentbit_output_opensearch_enabled: false
observability_fluentbit_output_opensearch_outputs:
  - alias: opensearch_all
    match: "*"
    index: "{{ observability_fluentbit_output_opensearch_index_all }}"
    host: "{{ observability_fluentbit_output_opensearch_host }}"
    host_port: "{{ observability_fluentbit_output_opensearch_host_port }}"
    user: "{{ observability_fluentbit_output_opensearch_user }}"
    password: "{{ observability_fluentbit_output_opensearch_password }}"
  # Host operating system log files like /var/log/auth.log /var/log/syslog /var/log/dpkg.log /var/log/mail.log
  - alias: opensearch_system_logs
    match: "host.file.*"
    index: "{{ observability_fluentbit_output_opensearch_index_system_logs }}"
    host: "{{ observability_fluentbit_output_opensearch_host }}"
    host_port: "{{ observability_fluentbit_output_opensearch_host_port }}"
    user: "{{ observability_fluentbit_output_opensearch_user }}"
    password: "{{ observability_fluentbit_output_opensearch_password }}"

observability_fluentbit_output_opensearch_host: !!null
observability_fluentbit_output_opensearch_host_port: !!null
observability_fluentbit_output_opensearch_user: !!null
observability_fluentbit_output_opensearch_password: !!null

observability_fluentbit_output_opensearch_index_all: !!null
observability_fluentbit_output_opensearch_index_system_logs: !!null
