---

- name: Backup of Mongo data
  hosts: mongo_servers[0]
  become: True
  gather_facts: True
  roles:
    - role: backups
      vars:
        backup_mongo: True

- name: Backup of Mysql data
  hosts: openedx_backup_mysql_server
  become: True
  gather_facts: True
  roles:
    - role: backups
      when: openedx_backup_mysql_server
      vars:
        backup_mysql: True
        backup_mysql_login_user: "{{ openedx_backup_mysql_login_user }}"
        backup_mysql_login_password: "{{ openedx_backup_mysql_login_password }}"

- name: Backup of richie primary data
  hosts: richie_primary
  become: True
  gather_facts: True
  roles:
    - nau_backup
