---

- name: Backup of Mongo data
  hosts: mongo_servers[0]
  become: True
  gather_facts: True
  roles:
    - role: backups
      vars:
        backup_mongo: True

- name: Backup of Mysql data
  hosts: nau_docker_swarm_servers
  become: True
  gather_facts: True
  roles:
    - role: backups
      when: openedx_mysql_replica_server == inventory_hostname
      vars:
        backup_mysql: True
        backup_mysql_container_name: "{{ openedx_backup_mysql_container_name }}"
        backup_mysql_login_user: "{{ openedx_backup_mysql_login_user }}"
        backup_mysql_login_password: "{{ openedx_backup_mysql_login_password }}"

    - role: backups
      when: richie_mysql_replica_server == inventory_hostname
      vars:
        backup_mysql: True
        backup_mysql_container_name: "{{ richie_backup_mysql_container_name }}"
        backup_mysql_login_user: "{{ richie_backup_mysql_login_user }}"
        backup_mysql_login_password: "{{ richie_backup_mysql_login_password }}"
