# Build web server nginx docker image for openedx.
#
# It will push a new docker image to Docker Hub, one per NAU environment (dev, stage and prod).
#
# Example for dev:
#   docker.io/nauedu/openedx-nginx:dev
#
# Open edX: https://hub.docker.com/r/nauedu/openedx-nginx/tags
#
# This playbook should be called before each deploy, or the deploy playbook should enable the
# build parameter.
#
# Example to build openedx:
#   ansible-playbook -i nau-data/envs/development/hosts.ini build_web_server.yml -e openedx_nginx_build=true
#
---
- name: Build web server nginx with static assets
  hosts: "openedx_docker_servers:&{{ target | default( groups['openedx_docker_servers'][0] ) }}"
  become: True
  gather_facts: True
  roles:
    - name: Build openedx project
      role: openedx_docker_deploy
      vars:
        openedx_build_web_server_node: "{{ hostvars[groups['build_server'][0]].ansible_host }}"
