---
# Ansible playbook that deploys NAU.
#
#
# Open edX instance with 3 layers:
# - Load balancer servers
# - Persistence servers (mongo_servers, cache_servers and mysql_servers)
# - Application servers (app_servers & complementary_servers)
#
# NAU also has other services like:
# - richie for marketing site
# - static proxy service
# - fam servers that print course certificate to PDF
#
# Examples:
#   To deploy the application servers and deploy 2 servers at once run:
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit app_servers -e serial_number=2
#
#   To deploy the application servers and migrate the database changes
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit app_servers -e "migrate_db=yes"
#
#   To deploy the application servers with a specific themes version
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit app_servers -e "THEMES_VERSION=master"
#
#   To deploy the complementary servers and its services run:
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit complementary_servers
#
#   To deploy the load balancers run:
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit balancer_servers
#
#   To deploy IdP proxy servers run:
#     ansible-playbook -i nau-data/:nvs/<env>/hosts.ini deploy.yml --limit idpproxy_servers
#
#   To mark a server for maintenance, like load balancer or mysql server, append to the shell command arguments:
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --tags keepalived --limit slave_persistence_servers -e keepalived_priority=1
#   To mark a server back to normal state, run the same command without the --limit.
#
#   To update the OpenedX MySQL database grants run:
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml -e openedx_mysql_initialization=true --limit nau_docker_swarm_servers --tags docker_mysql_replication_additional_users
#
#   To deploy the openedx docker stack
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit nau_docker_swarm_managers -e openedx_deploy=true
#
#   To deploy the static proxy docker stack
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit nau_docker_swarm_managers -e staticproxy_deploy=true
#
#   To deploy the coursecertificate docker stack
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit nau_docker_swarm_managers -e coursecertificate_deploy=true
#
#   To deploy the richie stack
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit nau_docker_swarm_servers -e richie_deploy=true
#
#   To deploy the observability stack
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit nau_docker_swarm_servers -e observability_deploy=true
#
#   To install/upgrade or configure docker daemon on docker swarm nodes on a rolling deploy approach exec stack's health check
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit nau_docker_swarm_servers -e docker_deploy=true
#
#   To install/upgrade or configure docker daemon without health check
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit nau_docker_swarm_servers -e docker_deploy=true -e docker_deploy_healthcheck=false
#
#   To deploy the openedx docker stack and build the web server docker image
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit nau_docker_swarm_managers -e openedx_deploy=true -e openedx_nginx_build=true
#
#   To update the openedx databases and mysql user grants
#     ansible-playbook -i nau-data/envs/<env>/hosts.ini deploy.yml --limit nau_docker_swarm_servers -e openedx_deploy=true -e openedx_mysql_initialization=true --tags docker_mysql_replication_additional
#
- name: Bootstrap instances of 16.04
  hosts: all,!idpproxy_servers,!nau_docker_swarm_managers,!nau_docker_swarm_workers,!support_server,!build_server
  gather_facts: no
  become: true
  tasks:
    - import_role:
        name: python_minimal
      when: ansible_python_interpreter is not defined

- name: Bootstrap instances of Ubuntu 20.04
  hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Install pip
      import_role:
        name: geerlingguy.pip
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
    
    # https://github.com/georchestra/ansible/issues/55
    - name: On Ubuntu 20.04 or later, you need to install the acl package to becoming non privileged user.
      package:
        name: acl
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Bootstrap cnc with Ubuntu 20.04
  hosts: command_and_control_2004
  become: True
  gather_facts: True
  tasks:
    # to run openedx-lms-db-export.yml playbook that runs a script on the a docker container
    - name: Install docker
      import_role:
        name: geerlingguy.docker

- name: Infrastructure configuration
  hosts: all
  become: True
  gather_facts: True
  roles:
    - role: users
    - role: ssh_authorized_keys
    - role: ansible_pakiti_client

- name: Configure hosts file
  hosts: all,!support_server,!command_and_control,!build_server
  become: True
  gather_facts: True
  # vars defined on 02_hosts.yml
  roles: 
    - bertvv.hosts
  tags: hosts

- name: Configure load balancer docker
  # Deploy before on backup balancer, so if there is an error during the ansible deployment the primary continue to serve
  hosts: balancer_servers
  serial: "{{ serial_number | default(1) }}"
  become: True
  gather_facts: True
  roles:
    - role: keepalived
      vars: 
        keepalived_priority_value: 1 # Lower priority so the VIPs can swap to other machine.
      when: vrrp_instances is defined
    - role: geerlingguy.docker
    - role: ansible-firewall
    - role: ansible-docker-deploy
    - role: haproxy-netsnmp-perl
    - role: snmpd
    - role: nau_check_urls
    - role: keepalived
      vars:
        keepalived_priority_value: "{{ keepalived_priority }}"
      when: vrrp_instances is defined
  tags: load-balancer

- name: Configure mongo server instance
  hosts: mongo_servers
  become: True
  gather_facts: True
  roles:
    - role: swapfile
    - role: data_dirs
    - role: mongo_3_2
    - role: oraclejdk
    - role: es_kopf

- name: Configure the complementary server group
  hosts: complementary_servers
  serial: "{{ serial_number | default(1) }}"
  become: True
  gather_facts: True
  roles:
    - role: rolling_deploy
      vars:
        rolling_deploy_starting: true
      when: ( groups['complementary_servers'] | length ) > 1
    - role: remove_edx_apt_ppa_repo
    - role: swapfile
    - role: nginx
      nginx_sites:
      - insights
      - edx_notes_api
      - nau_nginx_status
    - role: nginx_default_static_site
      when: use_nginx_default_site
    - role: discovery
      when: COMMON_COMPLEMENTARY_APPLICATION_ROLES is defined and 'discovery' in COMMON_COMPLEMENTARY_APPLICATION_ROLES
    - role: ecommerce
      when: COMMON_COMPLEMENTARY_APPLICATION_ROLES is defined and 'ecommerce' in COMMON_COMPLEMENTARY_APPLICATION_ROLES
    - role: ecomworker
      when: COMMON_COMPLEMENTARY_APPLICATION_ROLES is defined and 'ecommerce' in COMMON_COMPLEMENTARY_APPLICATION_ROLES
    - role: edx_notes_api
      when: COMMON_COMPLEMENTARY_APPLICATION_ROLES is defined and 'edx_notes_api' in COMMON_COMPLEMENTARY_APPLICATION_ROLES
    - role: analytics_api
      when: COMMON_COMPLEMENTARY_APPLICATION_ROLES is defined and 'analytics_api' in COMMON_COMPLEMENTARY_APPLICATION_ROLES
    - role: insights
      when: COMMON_COMPLEMENTARY_APPLICATION_ROLES is defined and 'insights' in COMMON_COMPLEMENTARY_APPLICATION_ROLES
    - role: mfe_deployer
      when: COMMON_COMPLEMENTARY_APPLICATION_ROLES is defined and 'mfe' in COMMON_COMPLEMENTARY_APPLICATION_ROLES
    - role: web_server_monitoring
    - role: snmpd
    - role: nau_check_urls
    - role: rolling_deploy
      vars:
        rolling_deploy_starting: false
      when: ( groups['complementary_servers'] | length ) > 1

- name: Configure pipeline servers
  hosts: pipeline_servers
  become: True
  gather_facts: True
  vars:
    ANALYTICS_API_SERVICE_CONFIG: "When defined, we create the analytics-api users at the db"
  roles:
    - role: remove_edx_apt_ppa_repo
    - role: swapfile
    - role: edxlocal
    - analytics_pipeline
    - analytics_pipeline_configuration

# specific variables are configured on nau-data/envs/<env>/group_vars/idpproxy_servers.yml
- name: Configure Shibboleth IdP
  hosts: 
    - idpproxy_servers
  become: True
  gather_facts: True
  tags: 
    - idp
  roles:
    - role: server_files
      vars: 
        server_files: "{{ server_files_before }}"
    - shibboleth-3-4-4-centos7-lite/roles/check-system
    - shibboleth-3-4-4-centos7-lite/roles/system
    - shibboleth-3-4-4-centos7-lite/roles/httpd
    - shibboleth-3-4-4-centos7-lite/roles/tomcat
    - shibboleth-3-4-4-centos7-lite/roles/postgresql
    - shibboleth-3-4-4-centos7-lite/roles/shibboleth
    - shibboleth-3-4-4-centos7-lite/roles/shibboleth_files
    - role: shibboleth-3-4-4-centos7-lite/roles/cc-cmd
      when: install_cc_cmd is not defined or install_cc_cmd
    - shibboleth-3-4-4-centos7-lite/roles/performance
    - role: server_files
      vars: 
        server_files: "{{ server_files_after }}"

- name: Configure support server
  hosts: support_server
  become: True
  gather_facts: True
  roles:
    - role: geerlingguy.docker
    - role: openark_orchestrator

- name: Configure build server
  hosts: build_server
  tasks:
    - name: Install docker
      import_role:
        name: geerlingguy.docker
    - name: Install Java to run a Jenkins node
      import_role:
        name: geerlingguy.java
    - name: Install pip to build python based software
      import_role:
        name: geerlingguy.pip
    - name: Install virtualenv pip package to build python based software
      pip:
        name: virtualenv
    - name: Install python3.8-venv package to build python based software
      package:
        name: python3.8-venv
    - name: Allow ubuntu user to run docker builds
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: Install docker_image ansible module dependencies
      pip:
        name: docker-py

# We need to install/upgrade/configure docker service, one docker swarm node at a time and
# executing all docker stacks health checks before we upgrade the next docker node. Using this
# approach we can upgrade all the cluster with minimal service unavailability.
- name: Install Docker on docker swarm nodes using a rolling approach executing health check on each stack
  hosts: nau_docker_swarm_managers,nau_docker_swarm_workers
  serial: 1
  become: True
  gather_facts: True
  vars:
    _docker_deploy: "{{ docker_deploy | default(false) | bool }}"
    _docker_deploy_healthcheck: "{{ docker_deploy_healthcheck | default(true) | bool }}"
  tasks:
    - name: installs docker software
      import_role:
        name: geerlingguy.docker
      when: _docker_deploy

    - name: Run healthcheck Makefile target on each stack
      shell: make --no-print-directory -C {{ item }} healthcheck
      retries: "{{ healthcheck_retries | default(50) }}"
      delay: "{{ healthcheck_delay | default(30) }}"
      register: result
      until: result.rc == 0
      when: _docker_deploy and _docker_deploy_healthcheck and not ansible_check_mode
      changed_when: False
      with_items: "{{ docker_stacks }}"
      # Run only on the first primary manager
      delegate_to: "{{ groups['nau_docker_swarm_managers'][0] }}"

- name: Configure 1st docker swarm manager
  hosts: nau_docker_swarm_managers[0]
  # serial: "{{ serial_number | default(1) }}"
  become: True
  gather_facts: True
  vars:
    _docker_swarm_deploy: "{{ docker_swarm_deploy | default(false) | bool }}"
  tasks:
    - name: configures the swarm
      import_role:
        name: docker_swarm
      when: _docker_swarm_deploy
      vars:
        docker_swarm_manager: "{{ groups['nau_docker_swarm_managers'] }}"
        docker_swarm_worker: "{{ groups['nau_docker_swarm_workers'] }}"
        configure_labels: false
        # on ansible inventory each host has its IPv4 address on the `ansible_host` variable
        docker_swarm_node_advertise_addr: "{{ hostvars[inventory_hostname].ansible_host }}"

    - name: Copy multi stack healthcheck Makefile script
      template:
        src: "templates/global/Makefile"
        dest: "/nau/ops/Makefile"
      tags: global_healthcheck

- name: Configure other docker swarm nodes
  hosts: nau_docker_swarm_managers,nau_docker_swarm_workers
  become: True
  gather_facts: True
  vars:
    _docker_swarm_deploy: "{{ docker_swarm_deploy | default(false) | bool }}"
  tasks:
    - import_role:
        name: snmpd
    - import_role:
        name: snmpd_docker
    - name: configures the swarm
      import_role:
        name: docker_swarm
      when: _docker_swarm_deploy
      vars:
        docker_swarm_manager: "{{ groups['nau_docker_swarm_managers'] }}"
        docker_swarm_worker: "{{ groups['nau_docker_swarm_workers'] }}"
        # on ansible inventory each host has its IPv4 address on the `ansible_host` variable
        docker_swarm_node_advertise_addr: "{{ hostvars[inventory_hostname].ansible_host }}"

- name: Deploy docker stacks to the 1st docker swarm manager
  hosts: nau_docker_swarm_managers,nau_docker_swarm_workers
  become: True
  gather_facts: True
  vars:
    docker_swarm_manager_to_deploy: "{{ groups['nau_docker_swarm_managers'][0] }}"
    docker_swarm_cluster_group_length: "{{ groups['nau_docker_swarm_servers'] | length }}"
  roles:
    - name: Deploy openedx stack
      role: openedx_deploy
      vars:
        openedx_deploy_run: "{{ openedx_deploy | default(false) }}"
        openedx_deploy_create_volumes: "{{ openedx_deploy | default(false) }}"
        docker_swarm_build_node: "{{ hostvars[groups['build_server'][0]].ansible_host }}"

    - name: Deploy staticproxy stack
      role: staticproxy_deploy
      vars:
        staticproxy_deploy_run: "{{ staticproxy_deploy | default(false) }}"
        staticproxy_deploy_create_volumes: "{{ staticproxy_deploy | default(false) }}"

    - name: Deploy coursecertificate stack
      role: coursecertificate_deploy
      vars:
        coursecertificate_deploy_run: "{{ coursecertificate_deploy | default(false) }}"
        coursecertificate_deploy_create_volumes: "{{ coursecertificate_deploy | default(false) }}"

    - name: Deploy richie stack
      role: richie_deploy
      vars:
        richie_deploy_run: "{{ richie_deploy | default(false) }}"
        richie_deploy_create_volumes: "{{ richie_deploy | default(false) }}"
        docker_swarm_build_node: "{{ hostvars[groups['build_server'][0]].ansible_host }}"

    - name: Deploy observability stack
      role: observability_deploy
      vars:
        observability_deploy_run: "{{ observability_deploy | default(false) }}"
        observability_deploy_create_volumes: "{{ observability_deploy | default(false) }}"
