# Ansible playbook that reinstalls the docker service on all the servers.
---
- hosts: all
  serial: 1
  vars:
    docker_daemon_config_enabled: true
    docker_install_enabled: true
    rolling_deploy_enabled: true
  tasks:
    - import_role: 
        name: keepalived
      vars: 
        keepalived_priority: 1
      when: vrrp_instances is defined
    - name: force all notified handlers to run at this point
      meta: flush_handlers
    - import_role:
        name: rolling_deploy
      when: rolling_deploy_enabled | bool
      vars:
        rolling_deploy_starting: true
    - import_role:
        name: geerlingguy.docker
      when: docker_install_enabled | bool
    - import_role:
        name: docker_daemon
      when: docker_daemon_config_enabled | bool
    - name: force all notified handlers to run at this point
      meta: flush_handlers
    - import_role:
        name: nau_check_urls
    - import_role:
        name: rolling_deploy
      vars:
        rolling_deploy_starting: false
      when: rolling_deploy_enabled | bool
    - import_role: 
        name: keepalived
      when: vrrp_instances is defined
