# Ansible playbook that reinstalls the docker service on all the servers.
---
- hosts: all
  serial: 1
  tasks:
    - import_role: 
        name: keepalived
      vars: 
        keepalived_priority: 1
      when: vrrp_instances is defined
    - name: force all notified handlers to run at this point
      meta: flush_handlers
    - import_role:
        name: rolling_deploy
      vars:
        rolling_deploy_starting: true
    - import_role:
        name: geerlingguy.docker
    - import_role:
        name: docker_daemon
    - name: force all notified handlers to run at this point
      meta: flush_handlers
    - import_role:
        name: nau_check_urls
    - import_role:
        name: rolling_deploy
      vars:
        rolling_deploy_starting: false
    - import_role: 
        name: keepalived
      when: vrrp_instances is defined
