---
- hosts: all
  serial: 1
  tasks:
    - import_role: 
        name: keepalived
      vars: 
        keepalived_priority: 1
      when: vrrp_instances is defined
    - name: force all notified handlers to run at this point
      meta: flush_handlers
    - import_role:
        name: rolling_deploy
      vars:
        rolling_deploy_starting: true
    - import_role:
        name: docker
    - name: Remove docker-ce package
      apt:
        name: docker-ce
        state: absent
    - name: Install docker-ce-cli and docker-ce packages
      apt: 
        name:
          - docker-ce-cli
          - docker-ce
        state: present
    - name: Install docker-compose package
      apt: 
        name: docker-compose
        state: present
    - import_role:
        name: nau_check_urls
    - import_role:
        name: rolling_deploy
      vars:
        rolling_deploy_starting: false
    - import_role: 
        name: keepalived
      when: vrrp_instances is defined
