---
- name: Restart all apps on supervisord like lms and studio
  hosts: app_servers
  serial: 1 # each server
  become: True
  gather_facts: False
  roles: 
    - role: rolling_deploy
      vars:
        rolling_deploy_starting: true
      when: ( groups['app_servers'] | length ) > 1

    # using a role to execute a command because the import_role ansible feature was introduced after the 2.3 ansible version
    - role: execute
      vars:
        command_to_execute: /edx/bin/supervisorctl restart all

    - role: rolling_deploy
      vars:
        rolling_deploy_starting: false
      when: ( groups['app_servers'] | length ) > 1
