# Playbook that checks the health of the services.
#
# 1. Check databases replication used by the open edx platform:
# - MySQL DB
# - MongoDB
# - Elasticsearch
#
# 2. Run check urls for all the web servers
#
# Ansible playbook extra variables:
# - target_mysql_server - used to check only a subrange of MySQL databases for its health
# - target_mongo_server - used to change the default Mongo database instance where to check the health of the cluster
#
# Example:
#   ansible-playbook -i nau-data/envs/development/hosts.ini healthcheck.yml
#
---
- name: Check MySQL 5.6 Database instances
  hosts: "mysql_servers:&{{ target_mysql_server | default('mysql_servers') }}"
  become: True
  gather_facts: True
  tasks:
    - name: Check lag from primary
      shell: mysql -u root -e "show slave status\G" | grep "Seconds_Behind_Master" | awk '{print $2}'
      when: ( groups['mysql_servers'] | length ) > 1
      register: mysql_output
      changed_when: false
      
    - name: Fail if MySQL DB instance is too much behind
      fail:
        msg: Fail MySQL DB instance is too much behind
      # it is ok if the node is behind from 0 to 9 seconds lag
      when: ( groups['mysql_servers'] | length ) > 1 and mysql_output.stdout is not match("[0-9]")

- name: Check MySQL 5.7 Database instances
  hosts: nau_docker_swarm_servers
  become: True
  gather_facts: True
  tasks:
    - name: Check lag from primary
      shell: docker exec -it -e MYSQL_PWD={{ EDXAPP_MYSQL_PASSWORD_ADMIN }} $(docker ps --filter "name=openedx_{{ openedx_mysql_container.key }}" {% raw %} --format "{{.ID}}" {% endraw %}) bash -c "echo 'show slave status \G;' | mysql -u root" | grep "Seconds_Behind_Master" | awk '{print $2}'
      when: not openedx_mysql_container.value.primary and inventory_hostname == openedx_mysql_container.value.host_fqdn
      loop: "{{ openedx_mysql_containers | default({}) | dict2items }}"
      loop_control:
        label: "{{ openedx_mysql_container.key }}"
        loop_var: openedx_mysql_container
      register: mysql_outputs
      changed_when: false
      
    - debug:
        msg: "{{ mysql_outputs }}"
      when: ansible_verbosity > 0

    - name: Fail if MySQL DB instance is too much behind
      fail:
        msg: Fail MySQL DB instance is too much behind
      # it is ok if the node is behind from 0 to 9 seconds lag
      when: ( not ( mysql_output.skipped | default(false) ) ) and mysql_output.stdout is not match("[0-9]")
      loop: "{{ mysql_outputs.results }}"
      loop_control:
        loop_var: mysql_output
        label: "host: {{ mysql_output.openedx_mysql_container.value.host_fqdn }} container: {{ mysql_output.openedx_mysql_container.key }}"

- name: Check Mongo Database instances
  # we only need to run the commands on a single server, so we run by default on the first defined on the ansible
  hosts: "mongo_servers:&{{ target_mongo_server | default('mongo_servers') }}[0]"
  become: True
  gather_facts: True
  tasks:
    - name: Get MongoDB secondary nodes replication information
      shell: |
        mongo admin -u admin -p{{ MONGO_ADMIN_PASSWORD }} --host rs0/localhost --eval 'db.printSlaveReplicationInfo()' | grep "behind the primary" | awk '{print $1}' | egrep "^[0-9]$" | wc -l
      register: mongo_db_secoundary_nodes_result
      changed_when: false
      
    - name: Fail if MongoDB secondary nodes replication isn't ok
      fail:
        msg: Fail the number of healthy secundary nodes
      when: mongo_db_secoundary_nodes_result.stdout != ( (( groups['mongo_servers'] | length) -1) | string )

    - name: Get Elasticsearch cluster health
      shell: |
        curl -s -X GET 'localhost:9200/_cluster/health?pretty' | grep 'number_of_nodes' | egrep -o '[0-9]+'
      args:
        warn: false
      register: es_nodes_result
      changed_when: false
      
    - name: Fail if Elasticsearch secondary nodes replication isn't ok
      fail:
        msg: Fail the number of healthy secundary nodes
      when: es_nodes_result.stdout != (( groups['mongo_servers'] | length) | string )
    
    - name: Check Elasticsearch cluster, indexes and shards health
      shell: curl -s -X GET 'localhost:9200/_cluster/health?level=shards&pretty' | egrep -o "status.*\," | sort | uniq | egrep -o "\"[^\ ]+\""
      args:
        warn: false
      register: es_shards_result
      changed_when: false

    - set_fact:
        # if its a single server there isn't the number of replicas to be on green status
        expected_status: "{{ 'green' if ( groups['mongo_servers'] | length) > 1 else 'yellow' }}"
      
    - name: Fail if Elasticsearch cluster, indexes and shards health isn't ok
      fail:
        msg: Fail the Elasticsearch cluster, indexes and shards health
      when: es_shards_result.stdout != ( '"' + expected_status + '"' )

- name: Check URLs
  hosts: all
  become: True
  gather_facts: True
  roles:
    - nau_check_urls
