# Playbook that checks the health of the services.
#
# 1. Check databases replication used by the open edx platform:
# - MySQL DB
# - MongoDB
# - Elasticsearch
#
# 2. Run check urls for all the web servers
#
# Ansible playbook extra variables:
# - target_mysql_server - used to check only a subrange of MySQL databases for its health
# - target_mongo_server - used to change the default Mongo database instance where to check the health of the cluster
#
# Example:
#   ansible-playbook -i nau-data/envs/development/hosts.ini healthcheck.yml
#
---
- name: Run Makefile healthcheck
  hosts: all
  become: True
  gather_facts: True
  serial: "{{ serial_number | default(1) }}" # check in sequence
  tasks:
    - name: Run Makefile healthcheck
      shell: make --no-print-directory -C {{ item }} healthcheck
      retries: "{{ healthcheck_retries | default(50) }}"
      delay: "{{ healthcheck_delay | default(30) }}"
      register: result
      until: result.rc == 0
      when: makefile_healthcheck is defined
      changed_when: False
      with_items: "{{ makefile_healthcheck }}"

- name: Check URLs
  hosts: all
  become: True
  gather_facts: True
  roles:
    - nau_check_urls

- name: Check URLs on docker swarm services
  hosts: nau_docker_swarm_managers[0]
  become: True
  gather_facts: True
  vars:
    _docker_stacks: "{{ docker_stacks | default([]) }}"
  tasks:
    - name: Check urls for openedx
      import_role:
        name: openedx_deploy
      vars:
        openedx_deploy_run: false
        healthcheck: true
      when: openedx_docker_deploy_base_folder is defined and openedx_docker_deploy_base_folder in _docker_stacks
      tags: nau_check_urls

    # - name: Check urls for staticproxy
    #   import_role:
    #     name: staticproxy_deploy
    #   vars:
    #     staticproxy_deploy_run: false
    #     healthcheck: true
    #   when: staticproxy_docker_deploy_base_folder is defined and staticproxy_docker_deploy_base_folder in _docker_stacks
    #   tags: nau_check_urls

    # - name: Check urls for coursecertificate
    #   import_role:
    #     name: coursecertificate_deploy
    #   vars:
    #     coursecertificate_deploy_run: false
    #     healthcheck: true
    #   when: coursecertificate_docker_deploy_base_folder is defined and coursecertificate_docker_deploy_base_folder in _docker_stacks
    #   tags: nau_check_urls

    # - name: Check urls for richie
    #   import_role:
    #     name: richie_deploy
    #   vars:
    #     richie_deploy_run: false
    #     healthcheck: true
    #   when: richie_docker_deploy_base_folder is defined and richie_docker_deploy_base_folder in _docker_stacks
    #   tags: nau_check_urls
