---

- name: Update and publish the nau_translation project
  hosts: app_servers
  become: True
  gather_facts: False
  tasks:

    - name: Update the repository
      git:
        repo: ssh://git@gitlab.fccn.pt/nau/nau_translations.git
        dest: /edx/var/i18n_nau/nau_translations
      register: git_pull
      when: nau_translations_update_repo is defined and nau_translations_update_repo == 'true'

    - name: Get last commit message
      shell: git log -1
      args:
        chdir: /edx/var/i18n_nau/nau_translations
      register: git_log
      when: nau_translations_update_repo is defined and nau_translations_update_repo == 'true'

    - name: Print the output of git updating and nau_translations_update_repo
      debug:
        var: git_log.stdout_lines
      when: nau_translations_update_repo is defined and nau_translations_update_repo == 'true'

    - name: Run the publish script from the project directory
      shell: /edx/var/i18n_nau/nau_translations/bin/publish_native
      register: publish_output

    - name: Print the output of publishing
      debug:
        var: publish_output.stdout_lines
