---

# Open edX instance with 3 layers:
# - Load balancer servers
# - Persistence servers
# - Application servers (application group & complementary group)

- name: Bootstrap instances of 16.04
  hosts: all
  gather_facts: no
  become: true
  roles:
    - python_minimal


- name: Configure db server instance
  hosts: mysql_servers
  become: True
  gather_facts: True
  roles:
    - role: keepalived

