# Issue Let's Encrypt https ssl certificates.
#
# It is used the certbot on standalone mode on the HAProxy load balancer.
# After the certificates are issued or renewed, they are copied to a Ceph S3 bucket.
# Then all certificates are downloaded on all HAProxy load balancer instances
# and the HAProxy is updated live to know new certificate and key.
# The certificate and its key is also downloaded on Open edX app servers,
# so they can be used by nginx using a docker volume. It's run nginx check
# configuration and then it's run nginx reload configuration command.
#
# The domains that we are going to issue the certificate are defined on 
# `letsencrypt_domains_to_issue_certs` variable.
#
# Example to run Let's Encrypt for all configured domains:
#    ansible-playbook -i nau-data/envs/<env>/hosts.ini letsencrypt.yml
#
# Example to run Let's Encrypt to a single domain, 
# nevertheless all certificates are updated on HAProxy and Open edX nginx.
#    ansible-playbook -i nau-data/envs/<env>/hosts.ini letsencrypt.yml -e '{"letsencrypt_domains_to_issue_certs": ["custom-domain.example.com"]}'
#
# Add the new domain to the `letsencrypt_domains_to_issue_certs` variable.
# Configure the new domain to copy certificate and key on the `openedx_docker_servers.yml` file 
# on the environment.
#
# To force the re-issue of the certificates.
# Warning about Let's Encrypt limit of 5 certificates in 7 days per domain.
#    -e letsencrypt_force_issue=true
#
---
- name: (Re)Issue ssl https certificates using Let's Encrypt
  hosts: balancer_servers[0]
  become: True
  gather_facts: True
  tasks:
    - name: (Re)Issue ssl https certificates using Let's Encrypt on primary HAProxy load balancer
      import_role:
        name: letsencrypt_issue
      vars:
        letsencrypt_certbot_email: alertas@nau.edu.pt
        letsencrypt_certbot_root_folder: /nau/ops/certbot/conf
        s3_host: "{{ AWS_S3_DBS_BACKUP_HOST }}"
        s3_host_bucket: "{{ AWS_S3_DBS_BACKUP_BUCKET_NAME }}"
        s3_path_prefix: "/letsencrypt_certificates"
        s3_access_key_id: "{{ EDXAPP_BACKUPS_AWS_ACCESS_KEY_ID }}"
        s3_secret_access_key: "{{ EDXAPP_BACKUPS_AWS_SECRET_ACCESS_KEY }}"


- name: Download Let's Encrypt certificates to HAProxy load balancers
  hosts: balancer_servers
  become: True
  gather_facts: True
  tasks:
    - name: Download and update certificates on HAProxy
      import_role:
        name: haproxy_update_certs
      vars:
        s3_host: "{{ AWS_S3_DBS_BACKUP_HOST }}"
        s3_host_bucket: "{{ AWS_S3_DBS_BACKUP_BUCKET_NAME }}"
        s3_path_prefix: "/letsencrypt_certificates"
        s3_access_key_id: "{{ EDXAPP_BACKUPS_AWS_ACCESS_KEY_ID }}"
        s3_secret_access_key: "{{ EDXAPP_BACKUPS_AWS_SECRET_ACCESS_KEY }}"
        haproxy_certs_folder: "{{ docker_deploy_base_folder }}/certs"
      tags: haproxy_update_certs

- name: Download Let's Encrypt certificates to nginx on Open edX app servers
  hosts: openedx_docker_servers
  become: True
  gather_facts: True
  vars:
    certificates_folder: "{{ openedx_docker_deploy_base_folder }}/nginx/ssl"
    s3_host: "{{ AWS_S3_DBS_BACKUP_HOST }}"
    s3_host_bucket: "{{ AWS_S3_DBS_BACKUP_BUCKET_NAME }}"
    s3_path_prefix: "/letsencrypt_certificates"
    s3_access_key_id: "{{ EDXAPP_BACKUPS_AWS_ACCESS_KEY_ID }}"
    s3_secret_access_key: "{{ EDXAPP_BACKUPS_AWS_SECRET_ACCESS_KEY }}"
  tasks:

    - name: Install required packages
      package:
        name: s3cmd
        state: present
      tags:
        - openedx_update_certs
        - install

    - name: Download Let's Encrypt certificates
      vars:
        s3cmd_prefix: s3cmd get --force --host {{ s3_host }} --host-bucket {{ s3_host_bucket }}
      shell: "{{ s3cmd_prefix }} s3://{{ s3_host_bucket }}{{ s3_path_prefix }}/{{ domain }}.pem     {{ certificates_folder }}/{{ domain }}.pem && \
              {{ s3cmd_prefix }} s3://{{ s3_host_bucket }}{{ s3_path_prefix }}/{{ domain }}.pem.key {{ certificates_folder }}/{{ domain }}.pem.key"
      environment:
        AWS_ACCESS_KEY_ID: "{{ s3_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ s3_secret_access_key }}"
      loop: "{{ letsencrypt_domains_to_issue_certs }}"
      loop_control:
        loop_var: domain
      tags: openedx_update_certs

    - name: nginx check config
      shell: make --no-print-directory --directory {{ openedx_docker_deploy_base_folder }} check-config-nginx
      tags:
        - openedx_update_certs
        - nginx
        - ngxin_check_config

    - name: nginx reload
      shell: make --no-print-directory --directory {{ openedx_docker_deploy_base_folder }} reload-nginx
      tags:
        - openedx_update_certs
        - nginx
        - ngxin_reload

    - name: Run Makefile healthcheck
      shell: make --jobs 20 --no-print-directory --directory {{ item }} healthcheck
      retries: "{{ healthcheck_retries | default(50) }}"
      delay: "{{ healthcheck_delay | default(30) }}"
      register: result
      until: result.rc == 0
      when: makefile_healthcheck is defined
      changed_when: False
      with_items: "{{ makefile_healthcheck }}"
      tags:
        - openedx_update_certs
        - healthcheck
