---
- name: Run discovery django scripts on first complementary server
  hosts: complementary_servers[0]
  tasks:
    - name: Refresh course metadata, remove unused indexes and update index
      become: true # use sudo to run command using other user
      become_user: discovery # run command has discovery user
      args:
        executable: /bin/bash # use bash instead of sh so we could source venvs
      shell: |
        cd &&
        source venvs/discovery/bin/activate &&
        source discovery_env &&
        cd discovery &&
        ./manage.py refresh_course_metadata &&
        ./manage.py remove_unused_indexes &&
        ./manage.py update_index  --batch-size 80 --disable-change-limit
      register: discovery_output

    - name: Print stdout of refresh course metadata output
      debug:
        msg: "{{ discovery_output.stdout_lines }}"

    - name: Print stderr of refresh course metadata output
      debug:
        msg: "{{ discovery_output.stderr_lines }}"

- name: Run LMS cache on first app server
  hosts: app_servers[0]
  tasks:
    - name: LMS cache programs
      become: true # use sudo to run command using other user
      become_user: edxapp # run command has discovery user
      args:
        executable: /bin/bash # use bash instead of sh so we could source venvs
      shell: |
        cd
        source venvs/edxapp/bin/activate
        source edxapp_env
        cd edx-platform/
        ./manage.py lms cache_programs
      register: lms_cache_output

    - name: Print stdout of lms cache programs output
      debug:
        msg: "{{ lms_cache_output.stdout_lines }}"

    - name: Print stderr of lms cache programs output
      debug:
        msg: "{{ lms_cache_output.stderr_lines }}"
