---
- name: Configure load balancer docker for green nodes
  hosts: balancer_servers
  become: True
  gather_facts: True
  roles:
    - role: docker
    - role: docker_container
      haproxy_tcp_backends: '{{ haproxy_tcp_green_backends }}'

- name: Update and publish the nau_translation project
  hosts: app_servers_blue
  become: True
  gather_facts: False
  roles:
    - role: nau_i18n
      nau_translations_update_repo: true

- name: Configure load balancer docker for blue nodes
  hosts: balancer_servers
  become: True
  gather_facts: True
  roles:
    - role: docker_container
      haproxy_tcp_backends: '{{ haproxy_tcp_blue_backends }}'

- name: Update and publish the nau_translation project
  hosts: app_servers_green
  become: True
  gather_facts: False
  roles:
    - role: nau_i18n
      nau_translations_update_repo: true

- name: Configure load balancer docker for all nodes
  hosts: balancer_servers
  become: True
  gather_facts: True
  roles:
    - role: docker_container
