---

- name: Configure load balancer docker for green nodes
  hosts: balancer_servers
  become: True
  gather_facts: True
  roles:
    - role: docker
    - role: docker_container
      haproxy_tcp_backends: '{{ haproxy_tcp_green_backends }}'

- name: Configure the blue nodes
  hosts: app_servers_blue
  become: True
  gather_facts: True
  roles:
    - role: swapfile
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      nginx_default_sites:
      - lms
    - role: edxapp
      celery_worker: True
    - edxapp
    - forum
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST is defined and POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ""
    - role: logrotate_overrides
      when: COMMON_COMPLEMENTARY_APPLICATION_ROLES is defined and 'aws' in COMMON_COMPLEMENTARY_APPLICATION_ROLES
    - role: nau_i18n

- name: Configure load balancer docker for blue nodes
  hosts: balancer_servers
  become: True
  gather_facts: True
  roles:
    - role: docker_container
      haproxy_tcp_backends: '{{ haproxy_tcp_blue_backends }}'


- name: Configure the green nodes
  hosts: app_servers_green
  become: True
  gather_facts: True
  roles:
    - role: swapfile
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      nginx_default_sites:
      - lms
    - role: edxapp
      celery_worker: True
    - edxapp
    - forum
    - role: postfix_queue
      when: POSTFIX_QUEUE_EXTERNAL_SMTP_HOST is defined and POSTFIX_QUEUE_EXTERNAL_SMTP_HOST != ""
    - role: logrotate_overrides
      when: COMMON_COMPLEMENTARY_APPLICATION_ROLES is defined and 'aws' in COMMON_COMPLEMENTARY_APPLICATION_ROLES
    - role: nau_i18n

- name: Configure load balancer docker for all nodes
  hosts: balancer_servers
  become: True
  gather_facts: True
  roles:
    - role: docker_container
