---
- name: geerlingguy.firewall
  version: 2.3.1

- name: bertvv.hosts
  version: v1.2.0

#- name: shibboleth-idp
- src: git@gitlab.fccn.pt:nau/shibboleth-3-4-4-centos7-lite.git
  scm: git
  version: master

- name: geerlingguy.docker
  version: 3.0.0
