---
- name: bertvv.hosts
  version: v1.2.0

- src: git+https://github.com/fccn/shibboleth-3-4-4-centos7-lite.git
  version: a6802ea65f76ceadf40605aa19a7a05721cb74e7

- name: geerlingguy.docker
  version: 3.1.2

- src: git+https://github.com/fccn/ansible-firewall.git
  version: b4fd0250e3f7df4adf45b8b617264765ab1d3061

- src: git+https://github.com/fccn/ansible-docker-deploy.git
  version: 893635cc4db6b4210c7106ce863d5d573d97ce13
