---
- name: bertvv.hosts
  version: v1.2.0

- src: git+https://github.com/fccn/shibboleth-3-4-4-centos7-lite.git
  version: a6802ea65f76ceadf40605aa19a7a05721cb74e7

- name: geerlingguy.docker
  version: 3.1.2

- src: git+https://github.com/fccn/ansible-docker-deploy.git
  version: 5d67b543962c90dedcc9561223e628fb9e2abca8
