---
- name: Check current server is the primary
  hosts: richie_primary
  tasks:
    - name: Get Richie homepage
      uri:
        url: https://www.nau.edu.pt/
        method: GET
      register: resp
    - name: Verify that the Richie primary server is the one in use
      assert:
        that:
          - resp.x_backend_server == ansible_hostname
        fail_msg: "Current Richie responding server should be the primary"
        success_msg: "Current Richie responding server is the primary"

- name: Backup of richie primary data if it's ok
  hosts: richie_primary
  become: True
  gather_facts: True
  roles:
    - nau_check_urls
    - nau_backup

- name: Restore richie replica from backup and check if it is ok
  hosts: richie_replica
  become: True
  gather_facts: True
  roles:
    - nau_backup_restore
    - nau_check_urls
