---

- name: Backup of mysql data
  hosts: persistence_servers[0]
  become: True
  gather_facts: True
  roles:
    - role: backups
      vars:
        backup_mongo: True
        backup_mysql: True

- name: Backup of wordpress data and content
  hosts: wordpress_servers[0]
  become: True
  gather_facts: True
  roles:
    - wordpress_backup
