---

- name: Create root directory
  file:
    path: "{{ image_root_dir }}"
    state: directory

- name: Copy Dockerfile
  template:
    dest: "{{ image_root_dir }}/Dockerfile"
    src: "{{ dockerfile_template }}"
  register: dockerfile

- name: create context directories
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ context_dirs }}"
  when: context_dirs is defined and context_dirs != ''

- name: Copy Dockerfile context
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  with_items: "{{ context_files }}"
  register: context

- name:    Build docker image
  docker_image: 
     name: "{{docker_image_name}}"
     path: "{{ image_root_dir }}"
     force: yes
  when: dockerfile.changed or context.changed    

- name: Run the container with volumes
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}"
    detach: yes
    ports: "{{ container_ports }}" 
    tty: yes
    restart_policy: "{{ docker_restart_policy }}"
    volumes: "{{ docker_volumes }}"
  when: docker_volumes is defined and docker_volumes != '' and (docker_reload_command is undefined or dockerfile.changed)

- name: Run the container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}"
    detach: yes
    ports: "{{ container_ports }}"
    tty: yes
    restart_policy: "{{ docker_restart_policy }}"
  when: docker_volumes is not defined or docker_volumes == '' and (docker_reload__command is undefined or dockerfile.changed)

- name: Reload container with custom command
  shell: "{{ docker_reload_command }}"
  when: docker_reload_command is defined and docker_reload_command != ''
