---
- name: Configure authorized ssh key for linux users
  authorized_key:
    user: "{{ item.user }}"
    exclusive: "{{ item.exclusive }}"
    key: "{{ item['keys'] | join('\n') }}"
  loop_control:
    label: "user: {{ item.user }}{{ ' exclusivelly' if (item.exclusive|bool) else ''}} with {{ item['keys'] | length }} keys"
  when: item.when | default(true)
  with_items: "{{ authorized_keys_for_user }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: 
    - ssh
