---
- name: Allow external access to mysql users
  mysql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    priv: "{{ item.db }}{{ item.permissions | default('.*:ALL')}}"
    host: "{{ item.host | default(ip_app_server) }}"
    append_privs: yes
  when: item.db != None and item.db != '' and item.user != None and item.user != ''
  with_items: "{{ edxremote_database_users }}"
  when: install_mysql

- name: Change mysql bind address
  template: src=mysqld.cnf.j2 dest=/etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
   - restart mysql
  when: install_mysql

- name: Create directory for override systemd mysql configuration
  file:
    state: directory
    path: /etc/systemd/system/mysql.service.d
  tags: mysql-daemon
  when: install_mysql

- name: Override systemd mysql configuration
  template:
    src: systemd-mysql-override.conf.j2
    dest: /etc/systemd/system/mysql.service.d/override.conf
  tags: mysql-daemon
  notify:
   - restart mysql
  when: install_mysql

- name: Allow external access to memcache
  template: src=memcached.conf.j2 dest=/etc/memcached.conf
  when: install_memcached
  notify:
   - restart memcached
