---
- name: Allow external access to mysql users
  mysql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    priv: "{{ item.db }}{{ item.permissions | default('.*:ALL')}}"
    host: "{{ item.host | default(ip_app_server) }}"
    append_privs: yes
  when: item.db != None and item.db != '' and item.user != None and item.user != ''
  with_items: "{{ edxremote_database_users }}"

- name: Change mysql bind address
  template: src=mysqld.cnf.j2 dest=/etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
   - restart mysql

- name: Allow external access to memcache
  template: src=memcached.conf.j2 dest=/etc/memcached.conf
  notify:
   - restart memcached
