---
- name: Override the access nginx logrotate config
  template:
    dest: "/etc/logrotate.d/nginx-access"
    src: "edx_logrotate_nginx_access.j2"
    owner: root
    group: root
    mode: "0644"
  register: config_templates

- name: overriding s3 log sync script
  template:
    dest: "{{ aws_s3_sync_script }}"
    src: send-logs-to-s3.j2
    mode: 0755
    owner: root
    group: root
  when: COMMON_OBJECT_STORE_LOG_SYNC

- name: Create symlink for s3 log sync script
  file:
    state: link
    src: "{{ aws_s3_sync_script }}"
    dest: "{{ COMMON_OBJECT_STORE_LOG_SYNC_SCRIPT }}"
  when: COMMON_OBJECT_STORE_LOG_SYNC


- name: Check if files exist so the next task doesn't fail
  stat:
    path: "{{ item }}"
  register: motd_files_exist
  with_items:
    - "/etc/update-motd.d/10-help-text"
    - "/usr/share/landscape/landscape-sysinfo.wrapper"
    - "/etc/update-motd.d/51-cloudguest"
    - "/etc/update-motd.d/91-release-upgrade"

- name: Update the ssh motd on Ubuntu
  file:
    path: "{{ item.item }}"
    mode: "0644"
  when: vagrant_home_dir.stat.exists == False and ansible_distribution in common_debian_variants and item.stat.exists
  with_items: "{{ motd_files_exist.results }}"

