# Default configuration to build a nginx docker image with all static assets from each container 
# in the stack. It includes a previous and next version assets so we can deliver and rolling deploy
# on a control manner the stack.
---
# Variable that makes the nginx to be built
# -e openedx_nginx_build=true
openedx_nginx_build: false

# docker registry organization
openedx_build_web_server_docker_registry: docker.io
openedx_build_web_server_docker_repository: nauedu
openedx_build_web_server_docker_image: openedx-nginx
openedx_build_web_server_docker_swarm_service: openedx_nginx
openedx_build_web_server_docker_image_with_hash_fact_name: "openedx_nginx_image"

openedx_build_web_server_services_root: /openedx/staticfiles

# services that we should cache the static assets
openedx_build_web_server_services:
  - service: openedx_analyticsapi
    docker_image: "{{ openedx_analyticsapi_image }}"
    folder_origin: /openedx/analyticsapi/assets
    folder_destination: "{{ openedx_build_web_server_services_root }}/analyticsapi"
  - service: openedx_discovery
    docker_image: "{{ openedx_discovery_docker_image }}"
    folder_origin: /openedx/discovery/course_discovery/assets
    folder_destination: "{{ openedx_build_web_server_services_root }}/discovery"
  - service: openedx_insights
    docker_image: "{{ openedx_insights_image }}"
    folder_origin: /openedx/insights/assets
    folder_destination: "{{ openedx_build_web_server_services_root }}/insights"
  - service: openedx_cms
    docker_image: "{{ openedx_app_image }}"
    folder_origin: /openedx/staticfiles/
    folder_destination: "{{ openedx_build_web_server_services_root }}/cms"
  - service: openedx_lms
    docker_image: "{{ openedx_app_image }}"
    folder_origin: /openedx/staticfiles/
    folder_destination: "{{ openedx_build_web_server_services_root }}/lms"

openedx_nginx_lms_staticfiles_folders:
  - lms/next
  - lms/previous

openedx_nginx_cms_staticfiles_folders:
  - cms/next
  - cms/previous

openedx_nginx_insights_staticfiles_folders:
  - insights/next
  - insights/previous

openedx_nginx_discovery_staticfiles_folders:
  - discovery/previous
  - discovery/next
