---
- name: Make sure we can use htpasswd module
  apt: 
    pkg: python-passlib
    state: present
  when: wordpress_nginx_auth_basic_enable is defined and wordpress_nginx_auth_basic_enable
  tags:
    - wordpress

- name: Write out htpasswd file
  htpasswd:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: "{{ item.state  }}"
    path: "{{ image_root_dir }}/nginx/nginx.htpasswd"
  with_items: "{{ wordpress_nginx_auth_basic_users }}"
  when: wordpress_nginx_auth_basic_enable is defined and wordpress_nginx_auth_basic_enable
  tags:
    - wordpress

- name: Build theme
  command: "make build"
  args:
    chdir: "{{ wordpress_nau_theme_dest }}"
  when: wordpress_nau_theme_dest is defined
  tags:
    - wordpress
