{% import '_docker_deploy_helper.j2' as helper with context %}
# {{ ansible_managed }}
version: "3.8"

services:
  app:
    image: {{ coursecertificate_app_docker_image }}
    ports:
      - target:    {{ coursecertificate_app_docker_port_target | default(5000) }}
        published: {{ coursecertificate_app_docker_port_published | default(5000) }}
        protocol:  tcp
        mode:      ingress
{{ helper.service_configs(service='app') }}
{{ helper.service_secrets(service='app') }}
    deploy:
      replicas: {{ coursecertificate_app_replicas }}
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 100M
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
    healthcheck:
      test: ["CMD", "echo", "''", ">", "/dev/tcp/example.com/{{ coursecertificate_mysql_lb_haproxy_write_port | default(3306) }}", "&&", "echo", "''", ">", "/dev/tcp/example.com/{{ coursecertificate_mysql_lb_haproxy_readonly_port | default(3306) }}", "||", "exit", "1"]
      start_period: 3s
      retries: 10
      interval: 10s
      timeout: 10s

  nginx:
    image: {{ coursecertificate_nginx_image }}
    restart: always
    ports:
      - target: 80
        published: {{ coursecertificate_nginx_http_ingress_port }}
        protocol: tcp
        mode: ingress
      - target: 443
        published: {{ coursecertificate_nginx_https_ingress_port }}
        protocol: tcp
        mode: ingress
{{ helper.service_configs(service='nginx') }}
{{ helper.service_secrets(service='nginx') }}
    extra_hosts:
      - "{{ nau_ceph_host }}:{{ nau_ceph_s3_ip }}"
    deploy:
      replicas: {{ coursecertificate_nginx_replicas }}
      mode: replicated
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 5M
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
      placement:
        max_replicas_per_node: 1
{% if coursecertificate_docker_placement_constraints is defined and ( coursecertificate_docker_placement_constraints | length > 0 ) %}
        constraints:
{% for key, value in coursecertificate_docker_placement_constraints.items() %}
          - {{ key }} == {{ value }}
{% endfor %}
{% endif %}
    healthcheck:
      test: ["CMD", "echo", "''", ">", "/dev/tcp/example.com/80", "&&", "echo", "''", ">", "/dev/tcp/example.com/443", "||", "exit", "1"]
      start_period: 3s
      retries: 10
      interval: 10s
      timeout: 10s

{{ helper.configs() }}
{{ helper.secrets() }}
