---
# Remove old containers that this stack no longer use
openedx_docker_deploy_stack_prune: true

openedx_docker_deploy_stack_name: openedx
openedx_docker_deploy_stack_template: templates/docker-stack.yml
openedx_docker_deploy_base_folder: /nau/ops/openedx

openedx_docker_deploy_templates: "{{ openedx_docker_deploy_templates_default }}"
openedx_docker_deploy_templates_default: "{{
  openedx_base_docker_deploy_templates +
  openedx_app_docker_deploy_templates +
  openedx_mysql_docker_deploy_templates +
  openedx_nginx_docker_deploy_templates +
  openedx_haproxy_docker_deploy_templates +
  openedx_discovery_docker_deploy_templates +
  openedx_analyticsapi_docker_deploy_templates +
  openedx_insights_docker_deploy_templates +
  openedx_docker_deploy_templates_additional
}}"
openedx_base_docker_deploy_templates: "{{ openedx_base_docker_deploy_templates_default }}"
openedx_base_docker_deploy_templates_default:
  - src:  "{{ openedx_makefile_template | default('templates/Makefile') }}"
    dest: "{{ openedx_docker_deploy_base_folder }}/Makefile"
openedx_docker_deploy_templates_additional: []

openedx_docker_deploy_files: "{{ openedx_docker_deploy_files_default }}"
openedx_docker_deploy_files_default: "{{
  openedx_nginx_docker_deploy_files +
  openedx_app_docker_deploy_files +
  openedx_notes_docker_deploy_files +
  openedx_discovery_docker_deploy_files +
  openedx_analyticsapi_docker_deploy_files +
  openedx_insights_docker_deploy_files +
  openedx_docker_deploy_files_additional
}}"
openedx_docker_deploy_files_additional: []

openedx_docker_deploy_folders_additional: "{{
  openedx_mysql_docker_deploy_folders_additional +
  openedx_elasticsearch_docker_deploy_folders_additional +
  openedx_redis_docker_deploy_folders_additional
}}"
# + openedx_mongodb_docker_deploy_folders_additional
# ...

# Declare additional docker stack services,
# so they can be used to generate Makefile helper targets.
openedx_docker_deploy_services_additional: "{{
  (openedx_elasticsearch_containers.keys() | list) +
  (openedx_redis_containers.keys() | list) +
  (openedx_docker_deploy_services_additional_list)
}} "

openedx_docker_deploy_services_additional_list:
  - lms
  - lms-worker-default
  - lms-worker-high
  - lms-worker-high_mem
  - cms
  - cms-worker-default
  - cms-worker-high
  - app-job
  - smtp
  - forum
  - forum-job
  - notes
  - notes-job
  - discovery
  - discovery-job
  - analyticsapi-job

# By default we limit the number of cpus available to each container with half of the available 
# vCPUs on the deployed node. This assumes that each docker swarm node has a similar layout of
# available cores. With this configuration we prevent a docker container to use all resources 
# and impact on other containers and services.
openedx_limit_cpus: "{{ ansible_processor_vcpus / 2 | int }}"

openedx_docker_deploy_stack_verify_retries: 120
openedx_docker_deploy_stack_verify_delay: 60

openedx_docker_images_to_prefetch:
  - "{{ openedx_app_image }}"
