---
# Remove old containers that this stack no longer use
openedx_docker_deploy_stack_prune: true

openedx_docker_deploy_stack_name: openedx
openedx_docker_deploy_stack_template: templates/docker-stack.yml
openedx_docker_deploy_base_folder: /nau/ops/openedx

openedx_docker_deploy_templates: "{{ openedx_docker_deploy_templates_default }}"
openedx_docker_deploy_templates_default: "{{ openedx_base_docker_deploy_templates + openedx_app_docker_deploy_templates + openedx_mysql_docker_deploy_templates + openedx_nginx_docker_deploy_templates }}"
# + openedx_mongodb_docker_deploy_templates
# ...

openedx_base_docker_deploy_templates: "{{ openedx_base_docker_deploy_templates_default }}"
openedx_base_docker_deploy_templates_default:
  - src:  "{{ openedx_makefile_template | default('templates/Makefile') }}"
    dest: "{{ openedx_docker_deploy_base_folder }}/Makefile"

openedx_docker_deploy_files: "{{ openedx_docker_deploy_files_default }}"
openedx_docker_deploy_files_default: "{{ openedx_nginx_docker_deploy_files + openedx_app_docker_deploy_files }}"

openedx_docker_deploy_folders_additional: "{{ openedx_mysql_docker_deploy_folders_additional + openedx_elasticsearch_docker_deploy_folders_additional + openedx_redis_docker_deploy_folders_additional }}"
# + openedx_mongodb_docker_deploy_folders_additional
# ...

# Declare additional docker stack services, to they can be used to generate Makefile helper targets.
openedx_docker_deploy_services_additional: "{{ (openedx_elasticsearch_containers.keys() | list) + (openedx_redis_containers.keys() | list) + (openedx_docker_deploy_services_additional_list) }} "

openedx_docker_deploy_services_additional_list:
  - redis-sentinel
  - lms
  - lms-worker
  - cms
  - cms-worker
  - smtp

openedx_smtp_docker_image: "docker.io/devture/exim-relay:4.95-r0-2"
