---
# Remove old containers that this stack no longer use
openedx_docker_deploy_stack_prune: true

openedx_docker_deploy_stack_name: openedx
openedx_docker_deploy_stack_template: templates/docker-stack.yml
openedx_docker_deploy_base_folder: /nau/ops/openedx

openedx_docker_deploy_templates: "{{ openedx_base_docker_deploy_templates + openedx_mysql_docker_deploy_templates }}"
# + openedx_mongodb_docker_deploy_templates
# ...

openedx_base_docker_deploy_templates:
  - src:  "{{ openedx_makefile_template | default('templates/Makefile') }}"
    dest: "{{ openedx_docker_deploy_base_folder }}/Makefile"

openedx_docker_deploy_folders_additional: "{{ openedx_mysql_docker_deploy_folders_additional + openedx_elasticsearch_docker_deploy_folders_additional }}"
# + openedx_mongodb_docker_deploy_folders_additional
# ...

# Declare additional docker stack services, to they can be used to generate Makefile helper targets.
openedx_docker_deploy_services_additional:
  - elasticsearch_1
  - elasticsearch_2
  - elasticsearch_3
