---
openedx_discovery_replicas: 1
openedx_discovery_deploy_parallelism: 1
openedx_discovery_job: false
openedx_discovery_docker_image: overhangio/openedx-discovery:12.0.4
openedx_discovery_job_command: bash -c "python manage.py migrate --noinput && python manage.py install_es_indexes"

openedx_discovery_port: 8000 # 8381 is on development server
openedx_discovery_limit_cpus: "{{ openedx_limit_cpus }}"

openedx_discovery_nginx_ssl_certificate_docker_target: "{{ openedx_nginx_ssl_certificate_docker_target }}"
openedx_discovery_nginx_ssl_certificate_key_docker_target: "{{ openedx_nginx_ssl_certificate_key_docker_target }}"

openedx_discovery_docker_deploy_files:
  - src: files/discovery/nau_production.py
    dest: "{{ openedx_docker_deploy_base_folder }}/discovery/nau_production.py"
    service: discovery
    config_name: discovery_envs_nau_production
    docker_target: /openedx/discovery/course_discovery/settings/nau_production.py

openedx_discovery_docker_deploy_templates:
  - src_data:  "{{ openedx_discovery_cfg_settings | to_nice_yaml(indent=2, width=1337) }}" # default_flow_style=False didn't work
    dest: "{{ openedx_docker_deploy_base_folder }}/discovery/discovery.yml"
    service: discovery
    config_name: discovery_cfg_yml
    docker_target: "{{ DISCOVERY_CFG }}"

openedx_discovery_cfg_settings: "{{ openedx_discovery_cfg_settings_default | combine(openedx_discovery_cfg_settings_overrides, recursive=True) }}"
openedx_discovery_cfg_settings_overrides: {}
openedx_discovery_cfg_settings_default:
  BACKEND_SERVICE_EDX_OAUTH2_KEY: "{{ DISCOVERY_BACKEND_SERVICE_EDX_OAUTH2_KEY }}"
  BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL: "{{ COMMON_OAUTH_PUBLIC_URL_ROOT }}"
  BACKEND_SERVICE_EDX_OAUTH2_SECRET: "{{ DISCOVERY_BACKEND_SERVICE_EDX_OAUTH2_SECRET }}"
  CACHES:
    default:
      BACKEND: django_redis.cache.RedisCache
      KEY_PREFIX: discovery
      LOCATION: "redis://{% if OPENEDX_REDIS_USERNAME and OPENEDX_REDIS_PASSWORD %}{{ OPENEDX_REDIS_USERNAME }}:{{ OPENEDX_REDIS_PASSWORD }}@{% endif %}{{ OPENEDX_REDIS_HOST }}:{{ OPENEDX_REDIS_PRIMARY_PORT }}/{{ DISCOVERY_CACHE_REDIS_DB }}"
  # CORS_ORIGIN_WHITELIST:
  # - publisher.stage.nau.fccn.pt
  CSRF_COOKIE_SECURE: true
  # CSRF_TRUSTED_ORIGINS:
  # - publisher.stage.nau.fccn.pt
  DATABASES:
    default:
      ENGINE: "django.db.backends.mysql"
      NAME: "{{ DISCOVERY_DEFAULT_DB_NAME }}"
      USER: "{{ DISCOVERY_MYSQL_USER }}"
      PASSWORD: "{{ DISCOVERY_MYSQL_PASSWORD }}"
      HOST: haproxy
      PORT: 3306
      OPTIONS:
        init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
    read_replica:
        ENGINE: "django.db.backends.mysql"
        HOST: haproxy
        PORT: 3307
        NAME: "{{ DISCOVERY_DEFAULT_DB_NAME }}"
        USER: "{{ COMMON_MYSQL_READ_ONLY_USER }}"
        PASSWORD: "{{ COMMON_MYSQL_READ_ONLY_PASS }}"
        ATOMIC_REQUESTS: False,
  DEFAULT_PARTNER_ID: "{{ DISCOVERY_DEFAULT_PARTNER_ID }}"
  EDX_DRF_EXTENSIONS:
    OAUTH2_USER_INFO_URL: "{{ COMMON_LMS_BASE_URL }}/user_info"
  ELASTICSEARCH_CLUSTER_URL: "{{ openedx_elasticsearch_containers.keys() | list }}"
  EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
  EMAIL_HOST: "{{ OPENEDX_SMTP_HOST }}"
  EMAIL_HOST_PASSWORD: "{{ OPENEDX_SMTP_HOST_PASSWORD }}"
  EMAIL_HOST_USER: "{{ OPENEDX_SMTP_HOST_USER }}"
  EMAIL_PORT: "{{ OPENEDX_SMTP_PORT }}"
  # EMAIL_USE_TLS: "{{ OPENEDX_SMTP_USE_TLS | string }}"
  EMAIL_USE_SSL: "{{ OPENEDX_SMTP_USE_SSL }}"
  JWT_AUTH:
    JWT_AUTH_COOKIE_HEADER_PAYLOAD: "{{ EDXAPP_JWT_AUTH_COOKIE_HEADER_PAYLOAD }}"
    JWT_AUTH_COOKIE_SIGNATURE: "{{ EDXAPP_JWT_AUTH_COOKIE_SIGNATURE }}"
    JWT_AUTH_REFRESH_COOKIE: "{{ EDXAPP_JWT_AUTH_REFRESH_COOKIE }}"
    JWT_ISSUERS:
      - ISSUER: "{{ EDXAPP_LMS_ISSUER }}"
        AUDIENCE: 'SET-ME-PLEASE'
        SECRET_KEY: "{{ EDXAPP_JWT_SECRET_KEY }}"
    JWT_PUBLIC_SIGNING_JWK_SET: "{{ EDXAPP_JWT_PUBLIC_SIGNING_JWK_SET|string }}"
  LANGUAGE_CODE: en
  # MEDIA_STORAGE_BACKEND
  # OPENEXCHANGERATES_API_KEY
  PARLER_DEFAULT_LANGUAGE_CODE: en
  PARLER_LANGUAGES:
    1:
      - code: en
    default:
      fallbacks:
        - en
      hide_untranslated: 'False'
  PLATFORM_NAME: "{{ DISCOVERY_PLATFORM_NAME }}"
  SECRET_KEY: "{{ DISCOVERY_SECRET_KEY }}"
  SOCIAL_AUTH_EDX_OAUTH2_ISSUER: "{{ COMMON_LMS_BASE_URL }}"
  SOCIAL_AUTH_EDX_OAUTH2_KEY: "{{ DISCOVERY_SOCIAL_AUTH_EDX_OAUTH2_KEY }}"
  SOCIAL_AUTH_EDX_OAUTH2_LOGOUT_URL: "{{ COMMON_LMS_BASE_URL }}/logout"
  SOCIAL_AUTH_EDX_OAUTH2_SECRET: "{{ DISCOVERY_SOCIAL_AUTH_EDX_OAUTH2_SECRET }}"
  SOCIAL_AUTH_EDX_OAUTH2_URL_ROOT: "{{ COMMON_LMS_BASE_URL }}"

openedx_discovery_docker_environment_variables: "{{ openedx_discovery_docker_environment_variables_default }}"
openedx_discovery_docker_environment_variables_default:
  DJANGO_SETTINGS_MODULE: course_discovery.settings.nau_production
  DISCOVERY_CFG: "{{ DISCOVERY_CFG }}"
  ELASTICSEARCH_TIMEOUT: 60 # NAU custom configuration

DISCOVERY_CFG: /openedx/config.yml

COMMON_JWT_ISSUER: '{{ COMMON_OAUTH_URL_ROOT }}'
COMMON_OAUTH_URL_ROOT: '{{ COMMON_OAUTH_PUBLIC_URL_ROOT }}'
COMMON_OAUTH_BASE_URL: '{{ COMMON_LMS_BASE_URL }}'
COMMON_OAUTH_PUBLIC_URL_ROOT: '{{ COMMON_OAUTH_BASE_URL }}/oauth2'
DISCOVERY_CACHE_REDIS_DB: 2

DISCOVERY_DEFAULT_PARTNER_ID: 1
