---

openedx_elasticsearch_containers:
  elasticsearch_1:
    data: /data/openedx/elasticsearch_1/
    host_fqdn: "{{ openedx_elasticsearch_1_server }}"    
  elasticsearch_2:
    data: /data/openedx/elasticsearch_2/
    host_fqdn: "{{ openedx_elasticsearch_2_server }}"
  elasticsearch_3:
    data: /data/openedx/elasticsearch_3/
    host_fqdn: "{{ openedx_elasticsearch_3_server }}"


openedx_elasticsearch_docker_deploy_folders_additional:
  - dest: /data/openedx/elasticsearch_1/
    dir_owner: 1000
    dir_group: 1000
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_elasticsearch_1_server }}"
  - dest: /data/openedx/elasticsearch_2/
    dir_owner: 1000
    dir_group: 1000
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_elasticsearch_2_server }}"
  - dest: /data/openedx/elasticsearch_3/
    dir_owner: 1000
    dir_group: 1000
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_elasticsearch_3_server }}"

openedx_elasticsearch_cluster_initial_master_nodes: "{{ openedx_elasticsearch_containers.keys() | list | join(',') }}"

openedx_elasticsearch_1_server: !!null
openedx_elasticsearch_2_server: !!null
openedx_elasticsearch_3_server: !!null

openedx_sysctl_conf:
  vm.max_map_count: 262144
