---
openedx_nginx_image: nginx:1.22.0
openedx_nginx_replicas: 1

openedx_nginx_http: 80
openedx_nginx_http_ingress_port: 80

openedx_nginx_https: 443
openedx_nginx_https_ingress_port: 443

openedx_nginx_docker_deploy_templates:
  # nginx.conf
  - src: templates/nginx/nginx.conf
    dest: "{{ openedx_docker_deploy_base_folder }}/nginx/nginx.conf"
    config_name: nginx_conf
    service: nginx
    docker_target: /etc/nginx/nginx.conf

  # maps, additional configuration for nginx
  - src: templates/nginx/sites/maps.j2
    dest: "{{ openedx_docker_deploy_base_folder }}/nginx/sites/maps"
    config_name: nginx_site_maps
    service: nginx
    docker_target: /etc/nginx/sites-enabled/maps

  # default lms site
  - src: templates/nginx/sites/lms.j2
    dest: "{{ openedx_docker_deploy_base_folder }}/nginx/sites/lms"
    config_name: nginx_site_lms
    service: nginx
    docker_target: /etc/nginx/sites-enabled/lms

  # studio site
  - src: templates/nginx/sites/cms.j2
    dest: "{{ openedx_docker_deploy_base_folder }}/nginx/sites/cms"
    config_name: nginx_site_cms
    service: nginx
    docker_target: /etc/nginx/sites-enabled/cms

  # forum site
  - src: templates/nginx/sites/forum.j2
    dest: "{{ openedx_docker_deploy_base_folder }}/nginx/sites/forum"
    config_name: nginx_site_forum
    service: nginx
    docker_target: /etc/nginx/sites-enabled/forum

  # discovery site
  - src: templates/nginx/sites/discovery.j2
    dest: "{{ openedx_docker_deploy_base_folder }}/nginx/sites/discovery"
    config_name: nginx_site_discovery
    service: nginx
    docker_target: /etc/nginx/sites-enabled/discovery

  # notes site
  - src: templates/nginx/sites/notes.j2
    dest: "{{ openedx_docker_deploy_base_folder }}/nginx/sites/notes"
    config_name: nginx_site_notes
    service: nginx
    docker_target: /etc/nginx/sites-enabled/notes

  # insights site
  - src: templates/nginx/sites/insights.j2
    dest: "{{ openedx_docker_deploy_base_folder }}/nginx/sites/insights"
    config_name: nginx_site_insights
    service: nginx
    docker_target: /etc/nginx/sites-enabled/insights

openedx_nginx_docker_deploy_files:
  # ssl crt
  - src: "{{ openedx_nginx_ssl_certificate }}"
    dest: "{{ openedx_docker_deploy_base_folder }}/nginx/ssl/certificate.crt.pem"
    secret_name: nginx_certificate_crt
    service: nginx
    docker_target: "{{ openedx_nginx_ssl_certificate_docker_target }}"
    when: "{{ openedx_nginx_ssl_certificate is defined }}"
  # ssl key
  - src: "{{ openedx_nginx_ssl_certificate_key }}"
    dest: "{{ openedx_docker_deploy_base_folder }}/nginx/ssl/certificate.key.pem"
    secret_name: nginx_certificate_key
    service: nginx
    docker_target: "{{ openedx_nginx_ssl_certificate_key_docker_target }}"
    when: "{{ openedx_nginx_ssl_certificate_key is defined }}"
  - dest: "{{ openedx_docker_deploy_base_folder }}/nginx/nginx.htpasswd"
    # don't copy the file because it is already there.
    docker_target: "{{ openedx_nginx_htpasswd_file }}"
    secret_name: nginx_htpasswd
    service: nginx
    when: "{{ openedx_nginx_basic_authentication_users is defined }}"

# openedx_nginx_basic_authentication_users: !!null
openedx_nginx_ssl_certificate_docker_target: /etc/ssl/certs/certificate.crt.pem
openedx_nginx_ssl_certificate_key_docker_target: /etc/ssl/private/certificate.key.pem
openedx_nginx_htpasswd_file: /etc/nginx/nginx.htpasswd

openedx_notes_nginx_ssl_certificate_docker_target: /etc/ssl/certs/certificate_notes.crt.pem
openedx_notes_nginx_ssl_certificate_key_docker_target: /etc/ssl/private/certificate_notes.key.pem

# a default site
openedx_nginx_lms_servers:
  - server_name: _
    default_server: true
    ssl_certificate: "{{ openedx_nginx_ssl_certificate_docker_target }}"
    ssl_certificate_key: "{{ openedx_nginx_ssl_certificate_key_docker_target }}"

openedx_nginx_cms_servers:
  - server_name: "{{ EDXAPP_CMS_BASE }}"
    ssl_certificate: "{{ openedx_nginx_ssl_certificate_docker_target }}"
    ssl_certificate_key: "{{ openedx_nginx_ssl_certificate_key_docker_target }}"

# from the old ansible configuration repository
COMMON_ENABLE_BASIC_AUTH: False
EDXAPP_LMS_ENABLE_BASIC_AUTH: "{{ COMMON_ENABLE_BASIC_AUTH }}"
NGINX_HSTS_MAX_AGE: 31536000
NGINX_P3P_MESSAGE: 'CP="Open edX does not have a P3P policy."'
