---
#
# Redis configurations
#
openedx_redis_docker_image: docker.io/bitnami/redis:6.2.7-debian-11-r49

openedx_redis_containers: "{{ openedx_redis_cluster_1_primary | combine(openedx_redis_cluster_1_replicas, recursive=True) | combine(openedx_redis_cluster_2, recursive=True) }}"

openedx_redis_cluster_1_primary:
  redis_c1p:
    host_fqdn: "{{ openedx_redis_cluster_1_primary_server }}"
    mode: master
    dest: /data/openedx/redis_c1p/
    dir_owner: 1001
    dir_group: 1001
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_redis_cluster_1_primary_server }}"

openedx_redis_cluster_1_replicas:
  redis_c1r1:
    host_fqdn: "{{ openedx_redis_cluster_1_replica_1_server }}"
    mode: slave
    dest: /data/openedx/redis_c1r1/
    dir_owner: 1001
    dir_group: 1001
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_redis_cluster_1_replica_1_server }}"
  redis_c1r2:
    host_fqdn: "{{ openedx_redis_cluster_1_replica_2_server }}"
    mode: slave
    dest: /data/openedx/redis_c1r2/
    dir_owner: 1001
    dir_group: 1001
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_redis_cluster_1_replica_2_server }}"

openedx_redis_cluster_2:
  redis_c2p:
    host_fqdn: "{{ openedx_redis_cluster_2_primary_server }}"
    backup: true
    dest: /data/openedx/redis_c2p/
    dir_owner: 1001
    dir_group: 1001
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_redis_cluster_2_primary_server }}"

openedx_redis_cluster_1_primary_container: "{{ openedx_redis_cluster_1_primary.keys() | first }}"
openedx_redis_cluster_2_primary_container: "{{ openedx_redis_cluster_2.keys() | first }}"

openedx_redis_docker_deploy_folders_additional: "{{ openedx_redis_containers.values() | list }}"

openedx_redis_cluster_1_primary_server: !!null
openedx_redis_cluster_1_replica_1_server: !!null
openedx_redis_cluster_1_replica_2_server: !!null
openedx_redis_cluster_2_primary_server: !!null
