---
#
# Redis configurations
#
openedx_redis_docker_image: docker.io/bitnami/redis:6.2.7
openedx_redis_primary_container: redis_1
openedx_redis_containers:
  redis_1:
    host_fqdn: "{{ openedx_redis_1_server }}"
    mode: master
    data: /data/openedx/redis_1/
  redis_2:
    host_fqdn: "{{ openedx_redis_2_server }}"
    mode: slave
    data: /data/openedx/redis_2/
  redis_3:
    host_fqdn: "{{ openedx_redis_3_server }}"
    mode: slave
    data: /data/openedx/redis_3/

openedx_redis_docker_deploy_folders_additional:
  - dest: /data/openedx/redis_1/
    dir_owner: 1001
    dir_group: 1001
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_redis_1_server }}"
  - dest: /data/openedx/redis_2/
    dir_owner: 1001
    dir_group: 1001
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_redis_2_server }}"
  - dest: /data/openedx/redis_3/
    dir_owner: 1001
    dir_group: 1001
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_redis_3_server }}"

openedx_redis_1_server: !!null
openedx_redis_2_server: !!null
openedx_redis_3_server: !!null

openedx_redis_sentinel_docker_image: docker.io/bitnami/redis-sentinel:6.2.7
openedx_redis_sentinel_replicas: 3
