---
#
# Redis configurations
#
openedx_redis_docker_image: docker.io/bitnami/redis:6.2.7-debian-11-r49

openedx_redis_containers:
  redis_1:
    host_fqdn: "{{ openedx_redis_1_server }}"
    mode: master
    dest: /data/openedx/redis_1/
    dir_owner: 1001
    dir_group: 1001
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_redis_1_server }}"
  redis_2:
    host_fqdn: "{{ openedx_redis_2_server }}"
    mode: master
    dest: /data/openedx/redis_2/
    dir_owner: 1001
    dir_group: 1001
    dir_mode: "0755"
    when: "{{ inventory_hostname == openedx_redis_2_server }}"

openedx_redis_docker_deploy_folders_additional: "{{ openedx_redis_containers.values() | list }}"

openedx_redis_1_server: !!null
openedx_redis_2_server: !!null
