---
# The lms/cms workers are celery processes that execute offline workloads.
# The worker celery processes are a configuration for how many OS processes that each
# replica will start.
openedx_lms_worker_replicas: 1
openedx_lms_worker_celery_processes: 1
openedx_cms_worker_replicas: 1
openedx_cms_worker_celery_processes: 1

openedx_lms_worker_limit_cpus: "{{ openedx_limit_cpus }}"
openedx_cms_worker_limit_cpus: "{{ openedx_limit_cpus }}"

#######################################
# LMS Worker - that run Celery tasks
#######################################
openedx_lms_worker_env_var: "{{ openedx_lms_env_var  | combine(openedx_lms_worker_env_var_default, recursive=True) | combine(openedx_lms_worker_env_var_overrides, recursive=True) }}"

openedx_lms_worker_env_var_default:
  C_FORCE_ROOT: "1" # run celery tasks as root #nofear

# per environment lms-worker environment variables
openedx_lms_worker_env_var_overrides: {}


#######################################
# CMS Worker - that run Celery tasks
#######################################
openedx_cms_worker_env_var: "{{ openedx_cms_env_var  | combine(openedx_cms_worker_env_var_default, recursive=True) | combine(openedx_cms_worker_env_var_overrides, recursive=True) }}"

openedx_cms_worker_env_var_default:
  C_FORCE_ROOT: "1" # run celery tasks as root #nofear

# per environment cms-worker environment variables
openedx_cms_worker_env_var_overrides: {}


######################################
# Workers
######################################
openedx_celery_workers:
  - service_variant: lms
    queue: default
    docker_image: "{{ openedx_app_image }}"
    environment_variables_dict: "{{ openedx_lms_worker_env_var }}"
    processes: "{{ openedx_lms_worker_celery_processes }}"
    deploy_replicas: "{{ openedx_lms_worker_replicas }}"
    deploy_max_replicas_per_node: "{{ ( openedx_lms_worker_replicas / ( docker_swarm_cluster_group_length | int ) ) | round(0, 'ceil') | int }}"
    deploy_constraint: "{{ openedx_lms_worker_deploy_constraint | default(false) | bool }}"
    deploy_constraint_label: docker_node_constraint_label_openedx_lms_worker
    deploy_resources_limit_memory: "{{ openedx_lms_worker_celery_processes * 1000 }}M"
    deploy_resources_limit_cpus: "{{ openedx_lms_worker_limit_cpus }}"
    deploy_resources_reservations_memory: "{{ openedx_lms_worker_celery_processes * 400 }}M"
  - service_variant: lms
    queue: high
    docker_image: "{{ openedx_app_image }}"
    environment_variables_dict: "{{ openedx_lms_worker_env_var }}"
    processes: "{{ openedx_lms_worker_celery_processes }}"
    deploy_replicas: "{{ openedx_lms_worker_replicas }}"
    deploy_max_replicas_per_node: "{{ ( openedx_lms_worker_replicas / ( docker_swarm_cluster_group_length | int ) ) | round(0, 'ceil') | int }}"
    deploy_constraint: "{{ openedx_lms_worker_deploy_constraint | default(false) | bool }}"
    deploy_constraint_label: docker_node_constraint_label_openedx_lms_worker
    deploy_resources_limit_memory: "{{ openedx_lms_worker_celery_processes * 1000 }}M"
    deploy_resources_limit_cpus: "{{ openedx_lms_worker_limit_cpus }}"
    deploy_resources_reservations_memory: "{{ openedx_lms_worker_celery_processes * 400 }}M"
  - service_variant: lms
    queue: high_mem
    docker_image: "{{ openedx_app_image }}"
    environment_variables_dict: "{{ openedx_lms_worker_env_var }}"
    processes: "{{ openedx_lms_worker_celery_processes }}"
    deploy_replicas: "{{ openedx_lms_worker_replicas }}"
    deploy_max_replicas_per_node: "{{ ( openedx_lms_worker_replicas / ( docker_swarm_cluster_group_length | int ) ) | round(0, 'ceil') | int }}"
    deploy_constraint: "{{ openedx_lms_worker_deploy_constraint | default(false) | bool }}"
    deploy_constraint_label: docker_node_constraint_label_openedx_lms_worker
    deploy_resources_limit_memory: "{{ openedx_lms_worker_celery_processes * 1000 }}M"
    deploy_resources_limit_cpus: "{{ openedx_lms_worker_limit_cpus }}"
    deploy_resources_reservations_memory: "{{ openedx_lms_worker_celery_processes * 400 }}M"
  - service_variant: cms
    queue: default
    docker_image: "{{ openedx_app_image }}"
    environment_variables_dict: "{{ openedx_cms_worker_env_var }}"
    processes: "{{ openedx_cms_worker_celery_processes }}"
    deploy_replicas: "{{ openedx_cms_worker_replicas }}"
    deploy_max_replicas_per_node: "{{ ( openedx_cms_worker_replicas / ( docker_swarm_cluster_group_length | int ) ) | round(0, 'ceil') | int }}"
    deploy_constraint: "{{ openedx_cms_worker_deploy_constraint | default(false) | bool }}"
    deploy_constraint_label: docker_node_constraint_label_openedx_cms_worker
    deploy_resources_limit_memory: "{{ openedx_cms_worker_celery_processes * 1000 }}M"
    deploy_resources_limit_cpus: "{{ openedx_cms_worker_limit_cpus }}"
    deploy_resources_reservations_memory: "{{ openedx_cms_worker_celery_processes * 400 }}M"
  - service_variant: cms
    queue: high
    docker_image: "{{ openedx_app_image }}"
    environment_variables_dict: "{{ openedx_cms_worker_env_var }}"
    processes: "{{ openedx_cms_worker_celery_processes }}"
    deploy_replicas: "{{ openedx_cms_worker_replicas }}"
    deploy_max_replicas_per_node: "{{ ( openedx_cms_worker_replicas / ( docker_swarm_cluster_group_length | int ) ) | round(0, 'ceil') | int }}"
    deploy_constraint: "{{ openedx_cms_worker_deploy_constraint | default(false) | bool }}"
    deploy_constraint_label: docker_node_constraint_label_openedx_cms_worker
    deploy_resources_limit_memory: "{{ openedx_cms_worker_celery_processes * 1000 }}M"
    deploy_resources_limit_cpus: "{{ openedx_cms_worker_limit_cpus }}"
    deploy_resources_reservations_memory: "{{ openedx_cms_worker_celery_processes * 400 }}M"
