---
- name: Make sure destination folder exists of shibboleth idp files to template and to get
  file:
    path: "{{ item.dest | dirname }}"
    state: directory
    recurse: yes
  with_items: "{{ shibboleth_idp_files_to_template + shibboleth_idp_files_to_get }}"

- name: Template additional shibboleth idp files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  with_items: "{{ shibboleth_idp_files_to_template }}"

- name: Get additional shibboleth idp files
  get_url:    
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    checksum: "{{ item.checksum | default('') }}"
  with_items: "{{ shibboleth_idp_files_to_get }}"
