---
openedx_aspects_import_tracking_logs_install: false
openedx_aspects_import_tracking_logs_run: false

openedx_aspects_import_tracking_logs_config_env_path: /nau/ops/openedx_aspects_import_trackinglogs/.env

openedx_aspects_import_trackinglogs_envs:
  ACCESS_KEY: access_key_s3
  SECRET_KEY: secret_key_s3
  ENDPOINT_URL: endpoints3
  BUCKET_NAME: bucket_name
  RALPH_ENDPOINT_URL: https://example.com/upload
  # Don't forgot to add the / at the end on PATH_S3_TO_TRACKINGLOG
  PATH_S3_TO_TRACKINGLOG: trackinglog/
  SHOW_PRINTS: True

import_trackinglogs_repo: https://github.com/fccn/import-tracking-logs
import_trackinglogs_base_directory: /nau/ops/
import_trackinglogs_version: v1.0
virtual_environment_path: nau/ops/