---
- name: Create folders volumes for observability stack
  file:
    dest: "{{ item.dest | dirname }}"
    owner: "{{ item.dir_owner|default(omit) }}"
    group: "{{ item.dir_group|default(omit) }}"
    mode: "{{ item.dir_mode | default(omit) }}"
    recurse: true
    state: directory
  when: (observability_deploy_create_volumes | default(false)) and (item.when | default(true) | bool)
  loop_control:
    label: "{{ item.dest }}"
  loop: "{{ observability_docker_deploy_folders_additional }}"
  tags:
    - docker_deploy

- name: Deploy
  include_role:
    name: ansible-docker-deploy
  vars:
    docker_deploy_stack_name:          "{{ observability_docker_deploy_stack_name }}"
    docker_deploy_stack_template:      "{{ observability_docker_deploy_stack_template }}"
    docker_deploy_base_folder:         "{{ observability_docker_deploy_base_folder }}"
    docker_deploy_templates:           "{{ observability_docker_deploy_templates | default([]) }}"
    docker_deploy_files:               "{{ observability_docker_deploy_files | default([]) }}"
    docker_deploy_folders_additional:  "{{ observability_docker_deploy_folders_additional | default([]) }}"
    docker_deploy_configs:             "{{ observability_docker_deploy_configs | default([]) }}"
    docker_deploy_secrets:             "{{ observability_docker_deploy_secrets | default([]) }}"
    docker_deploy_services_additional: "{{ observability_docker_deploy_services_additional | default([]) }}"
    docker_deploy_stack_prune:         "{{ observability_docker_deploy_stack_prune }}"
    docker_deploy_stack_verify_retries: "{{ observability_docker_deploy_stack_verify_retries }}"
    docker_deploy_stack_verify_delay:  "{{ observability_docker_deploy_stack_verify_delay }}"
  when: docker_swarm_manager_to_deploy is defined and docker_swarm_manager_to_deploy == inventory_hostname and observability_deploy_run | default(false)
  tags:
    - docker_deploy

- name: Template configs for aggregator node
  template:
    src: "{{ observability_extra_template.src }}"
    dest: "{{ observability_extra_template.dest }}"
  when: (observability_deploy_run | default(false)) and ( observability_extra_template.when | default(true) | bool )
  loop: "{{ observability_aggregator_node_templates }}"
  loop_control:
    label: "Template {{ observability_extra_template.dest }}"
    loop_var: observability_extra_template
  tags: docker_deploy

- name: Run healthcheck
  shell: make healthcheck
  args:
    chdir: "{{ observability_docker_deploy_base_folder }}"
  delay: "{{ observability_docker_deploy_stack_verify_delay }}"
  register: result
  until: result.rc == 0
  retries: "{{ observability_docker_deploy_stack_verify_retries }}"
  # run it only when deploying or when on healthcheck mode.
  when: docker_swarm_manager_to_deploy is defined and docker_swarm_manager_to_deploy == inventory_hostname and not ansible_check_mode and (observability_deploy_run | default(false)) or (healthcheck | default(false))
  changed_when: False
  tags: 
    - healthcheck
    - docker_deploy
