---
- name: Create folders volumes for observability stack
  file:
    dest: "{{ item.dest | dirname }}"
    owner: "{{ item.dir_owner|default(omit) }}"
    group: "{{ item.dir_group|default(omit) }}"
    mode: "{{ item.dir_mode | default(omit) }}"
    recurse: true
    state: directory
  when: (observability_deploy_create_volumes | default(false)) and (item.when | default(true) | bool)
  loop_control:
    label: "{{ item.dest }}"
  loop: "{{ observability_docker_deploy_folders_additional }}"
  tags:
    - docker_deploy

- name: Deploy
  include_role:
    name: ansible-docker-deploy
  when: docker_swarm_manager_to_deploy is defined and docker_swarm_manager_to_deploy == inventory_hostname and observability_deploy_run | default(false)
  tags:
    - docker_deploy

- name: Run healthcheck
  shell: make healthcheck
  args:
    chdir: "{{ observability_docker_deploy_base_folder }}"
  delay: "{{ docker_deploy_stack_verify_delay | default(15) }}"
  register: result
  until: result.rc == 0
  retries: "{{ observability_deploy_healthcheck_retries | default(30) }}" # 10 minutes of waiting
  # run it only when deploying or when on healthcheck mode.
  when: docker_swarm_manager_to_deploy is defined and docker_swarm_manager_to_deploy == inventory_hostname and not ansible_check_mode and (observability_deploy_run | default(false)) or (healthcheck | default(false))
  changed_when: False
  tags: 
    - healthcheck
    - docker_deploy
