---

- name: Create additional database users
  mysql_user:
    name: "{{ item.user }}"
    password: "{{ item.pass | default(omit) }}"
    login_host: "{{ _login_host }}"
    login_user: "{{ _login_user }}"
    login_password: "{{ _login_password }}"
    login_port: "{{ _login_port }}"
    priv: "{{ item.priv | default( item.db + '.*:ALL' ) }}"
    host: "{{ item.host | default('%') }}"
    state: present
  when: item.db != None and item.db != ''
  with_items: "{{ docker_mysql_replication_additional_users }}"
  tags:
    - docker_mysql_replication
    - docker_mysql_replication_additional
    - docker_mysql_replication_additional_users
