---
rolling_deploy_msg: "{{ 'Block' if ( rolling_deploy_starting | default('false') ) else 'Open' }}"
rolling_deploy_iptables_state: "{{ 'present' if ( rolling_deploy_starting | default('false') ) else 'absent' }}"
rolling_deploy_docker: false
rolling_deploy_chain: "{{ 'FORWARD' if rolling_deploy_docker else 'INPUT' }}"
rolling_deploy_parent_servers_ipv4: "{{ groups['balancer_servers'] | map('extract', hostvars, ['ansible_host']) | list }}"
rolling_deploy_parent_servers_ipv6: []
