---
- name: Deploy
  include_role:
    name: ansible-docker-deploy
  vars:
    docker_deploy_base_folder:         "{{ observability_docker_deploy_base_folder }}"
    docker_deploy_compose_template:    "{{ observability_docker_deploy_compose_template }}"
    docker_deploy_templates:           "{{ observability_docker_deploy_templates | default([]) }}"
    docker_deploy_files:               "{{ observability_docker_deploy_files | default([]) }}"
    docker_deploy_folders_additional:  "{{ observability_docker_deploy_folders_additional | default([]) }}"
    docker_deploy_configs:             "{{ observability_docker_deploy_configs | default([]) }}"
    docker_deploy_secrets:             "{{ observability_docker_deploy_secrets | default([]) }}"
    docker_deploy_services_additional: "{{ observability_docker_deploy_services_additional | default([]) }}"
    docker_deploy_shell: true
    docker_deploy_healthcheck_delay :  "{{ observability_docker_deploy_healthcheck_delay }}"
    docker_deploy_healthcheck_retries: "{{ observability_docker_deploy_healthcheck_retries }}"
  when: observability_docker_deploy | default(false)
  tags:
    - docker_deploy

- name: Run healthcheck
  shell: make healthcheck
  args:
    chdir: "{{ observability_docker_deploy_base_folder }}"
  delay: "{{ observability_docker_deploy_healthcheck_delay }}"
  register: result
  until: result.rc == 0
  retries: "{{ observability_docker_deploy_healthcheck_retries }}"
  # run it only when deploying or when on healthcheck mode.
  when: not ansible_check_mode and (observability_docker_deploy | default(false)) or (healthcheck | default(false))
  changed_when: False
  tags: 
    - healthcheck
    - docker_deploy
