---
# prefix all variables of ansible-docker-deploy role with the stack name
docker_deploy_stack_name:         "{{ staticproxy_docker_deploy_stack_name }}"
docker_deploy_stack_template:     "{{ staticproxy_docker_deploy_stack_template }}"
docker_deploy_base_folder:        "{{ staticproxy_docker_deploy_base_folder }}"
docker_deploy_templates:          "{{ staticproxy_docker_deploy_templates | default([]) }}"
docker_deploy_files:              "{{ staticproxy_docker_deploy_files | default([]) }}"
docker_deploy_folders_additional: "{{ staticproxy_docker_deploy_folders_additional | default([]) }}"
docker_deploy_configs:            "{{ staticproxy_docker_deploy_configs | default([]) }}"
docker_deploy_secrets:            "{{ staticproxy_docker_deploy_secrets | default([]) }}"

nau_urls_to_check: "{{ staticproxy_nau_urls_to_check }}"
