---
BACKUP_ROOT: "/var/nau_tmp"
BACKUP_DATE: "{{ ansible_date_time.date }}"
BACKUP_LOCATION: "{{BACKUP_ROOT}}/{{BACKUP_DATE}}.d"

AWS_S3_DBS_BACKUP_BUCKET_NAME: "SET ME PLEASE"
AWS_S3_DBS_BACKUP_HOST: "SET ME PLEASE"

EDXAPP_BACKUPS_AWS_ACCESS_KEY_ID: "SET ME PLEASE"
EDXAPP_BACKUPS_AWS_SECRET_ACCESS_KEY: "SET ME PLEASE"

BACKUP_COMMAND: make --directory={{ BACKUP_DIRECTORY }} backup
BACKUP_DIRECTORY: "{{ docker_deploy_base_folder }}"

# Need to define the variables:
# BACKUP_FILE: 
