---

- name: Ensure elasticsearch ownership
  file:
    dest: '/edx/var/elasticsearch/'
    state: directory
    owner: elasticsearch
    recurse: yes

# Kopf plugin

- name: install kopf plugin
  shell: >
    /usr/share/elasticsearch/bin/plugin --install lmenezes/elasticsearch-kopf/{{ ES_PLUGIN_KOPF_VERSION }}
  register: kopf_response
  ignore_errors: yes
  when:  ELASTICSEARCH_KOPF == true

- name: Kopf installation failed
  pause:
    prompt: "Kopf instllation Failed. Check error message {{ kopf_response.stdout }}"
  when: kopf_response.rc != 0

