---

- set_fact:
    web_server_monitoring_script_initial: "{{ web_server_monitoring_script_initial_docker }}"
  when: web_server_monitoring_mode is defined and web_server_monitoring_mode == 'docker'
  tags: web_server_monitoring

- set_fact:
    web_server_monitoring_script_initial: "{{ web_server_monitoring_script_initial_file }}"
  when: web_server_monitoring_mode is defined and web_server_monitoring_mode == 'file'
  tags: web_server_monitoring

- name: Create nginx monitoring folders
  file:
    dest: "{{ item.dest | dirname }}"
    owner: "{{ item.dir_owner|default(omit) }}"
    group: "{{ item.dir_group|default(omit) }}"
    mode: "{{ item.dir_mode | default(omit) }}"
    recurse: true
    state: directory
  with_items: "{{ web_server_monitoring_files }}"
  when: web_server_monitoring_script_initial is defined
  tags: web_server_monitoring

- name: Create nginx monitoring shell scripts
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    mode: "0755"
    owner: "{{ web_server_monitoring_owner | default(omit) }}"
    group: "{{ web_server_monitoring_group | default(omit) }}"
  with_items: "{{ web_server_monitoring_files }}"
  when: web_server_monitoring_script_initial is defined
  tags: web_server_monitoring

# Group adm is used for system monitoring tasks
- name: Adding existing user 'snmp' to group 'adm'. 
  user:
    name: snmp
    groups: adm
    append: yes # preserve other groups of snmp user
  tags: web_server_monitoring
