---

- set_fact:
    web_server_monitoring_script_initial: "{{ web_server_monitoring_script_initial_docker }}"
    web_server_monitoring_snmp_user_on_group: docker
  when: web_server_monitoring_mode is defined and web_server_monitoring_mode == 'docker'
  tags: web_server_monitoring

- set_fact:
    web_server_monitoring_script_initial: "{{ web_server_monitoring_script_initial_file }}"
    web_server_monitoring_snmp_user_on_group: adm
  when: web_server_monitoring_mode is defined and web_server_monitoring_mode == 'file'
  tags: web_server_monitoring

- name: Create nginx monitoring folders
  file:
    dest: "{{ item.dest | dirname }}"
    owner: "{{ item.dir_owner|default(omit) }}"
    group: "{{ item.dir_group|default(omit) }}"
    mode: "{{ item.dir_mode | default(omit) }}"
    recurse: true
    state: directory
  with_items: "{{ web_server_monitoring_files }}"
  when: web_server_monitoring_script_initial is defined
  tags: web_server_monitoring

- name: Create nginx monitoring shell scripts
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    mode: "0755"
    owner: "{{ web_server_monitoring_owner | default(omit) }}"
    group: "{{ web_server_monitoring_group | default(omit) }}"
  with_items: "{{ web_server_monitoring_files }}"
  when: web_server_monitoring_script_initial is defined
  tags: web_server_monitoring

# Group adm is used for system monitoring tasks
- name: Adding existing user 'snmp' to group '{{ web_server_monitoring_snmp_user_on_group }}'. 
  user:
    name: snmp
    groups: "{{ web_server_monitoring_snmp_user_on_group }}"
    append: yes # preserve other groups of snmp user
  notify: restart snmpd
  tags: web_server_monitoring

-  debug: msg="trigger snmpd-restart"
   notify: restart snmpd
   changed_when: true
   when: force_snmpd_restart | default(false)
