---
- name: Install keepalived packages
  apt:
    name: "{{ keepalived_packages }}"
    state: present
  tags: keepalived

- name: Adding keepalived configuration template
  template:
    dest: "/etc/keepalived/keepalived.conf"
    src: "keepalived.conf.j2"
  notify: restart keepalived
  tags: keepalived

- name: Ensure handlers are notified now to avoid run a next role without changing the keepalive priority
  meta: flush_handlers
