---
  - name: restart mysql
    systemd:
      state: restarted
      daemon_reload: yes
      name: mysql

  - name: restart memcached
    service: name=memcached state=restarted

  - name: restart rabbitmq
    service: name=rabbitmq-server state=restarted
