# Executed on the swarm manager
---
- name: Set default node labels
  set_fact:
    docker_swarm_node_labels_default:
      hostname: "{{ hostvars[ item ]['ansible_hostname'] }}"
      fqdn: "{{ hostvars[ item ]['ansible_fqdn'] }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  when: hostvars[item]['docker_swarm_node_labels_default'] is undefined
  loop: "{{ docker_swarm_manager + docker_swarm_worker }}"
  tags:
    - swarm
    - swarm-manager
    - swarm-worker
    - swarm-labels

- name: Replace docker swarm node labels
  docker_node:
    hostname: "{{ item }}"
    labels: "{{ hostvars[item]['docker_swarm_node_labels_default'] | combine( hostvars[ item ]['docker_swarm_node_labels_extend'] if hostvars[ item ]['docker_swarm_node_labels_extend'] is defined else {} ) }}"
    labels_state: replace
  loop: "{{ docker_swarm_worker + docker_swarm_manager }}"
  tags:
    - swarm
    - swarm-manager
    - swarm-worker
    - swarm-labels
