---
- name: Init a new swarm with default parameters on first docker swarm manager
  docker_swarm:
    state: present
    advertise_addr: "{{ docker_swarm_node_advertise_addr }}"
  register: result_output
  when: inventory_hostname == docker_swarm_manager[0]
  tags:
    - swarm
    - swarm-manager

- name: Sets swarm manager facts
  set_fact:
    swarm_facts: "{{ result_output }}"
  tags:
    - swarm
    - swarm-manager

- name: Inspect swarm (swarm_facts not available)
  docker_swarm_info:
  register: swarm
  delegate_to: "{{ docker_swarm_manager[0] }}"
  when: inventory_hostname != docker_swarm_manager[0]
  tags:
    - swarm
    - swarm-worker

- name: Adds additional docker swarm manager nodes
  docker_swarm:
    state: join
    advertise_addr: "{{ docker_swarm_node_advertise_addr }}"
    join_token: "{{ swarm['swarm_facts']['JoinTokens']['Manager'] }}"
    remote_addrs: [ "{{ hostvars[docker_swarm_manager[0]]['ansible_default_ipv4']['address'] }}:{{ docker_swarm_port_cluster_management }}" ]
  when: inventory_hostname != docker_swarm_manager[0]
  tags:
    - swarm
    - swarm-manager
