---
- name: Inspect swarm (swarm_facts not available)
  docker_swarm_info:
  register: swarm
  delegate_to: "{{ docker_swarm_manager[0] }}"
  when: hostvars[ docker_swarm_manager[0] ]['swarm_facts'] is undefined
  tags:
    - swarm
    - swarm-worker

- name: Collect swarm facts
  set_fact:
    swarm: "{{ hostvars[ docker_swarm_manager[0] ]['swarm_facts'] }}"
  when: hostvars[ docker_swarm_manager[0] ]['swarm_facts'] is not undefined
  tags:
    - swarm
    - swarm-worker

# - name: Collect docker swarm manager facts
#   setup:
#   delegate_to: "{{ docker_swarm_manager[0] }}"
#   delegate_facts: true
#   when: hostvars[docker_swarm_manager[0]] is undefined
#   tags:
#     - swarm
#     - swarm-worker

- name: Adds node
  docker_swarm:
    state: join
    advertise_addr: "{{ docker_swarm_node_advertise_addr }}"
    join_token: "{{ swarm['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ "{{ hostvars[docker_swarm_manager[0]]['ansible_default_ipv4']['address'] }}:{{ docker_swarm_port_cluster_management }}" ]
  tags:
    - swarm
    - swarm-worker
