---
# prefix all variables of ansible-docker-deploy role with the stack name
docker_deploy_stack_name:          "{{ observability_docker_deploy_stack_name }}"
docker_deploy_stack_template:      "{{ observability_docker_deploy_stack_template }}"
docker_deploy_base_folder:         "{{ observability_docker_deploy_base_folder }}"
docker_deploy_templates:           "{{ observability_docker_deploy_templates | default([]) }}"
docker_deploy_files:               "{{ observability_docker_deploy_files | default([]) }}"
docker_deploy_folders_additional:  "{{ observability_docker_deploy_folders_additional | default([]) }}"
docker_deploy_configs:             "{{ observability_docker_deploy_configs | default([]) }}"
docker_deploy_secrets:             "{{ observability_docker_deploy_secrets | default([]) }}"
docker_deploy_services_additional: "{{ observability_docker_deploy_services_additional | default([]) }}"
docker_deploy_stack_prune:         "{{ observability_docker_deploy_stack_prune }}"

