---
- name: Install docker-compose
  package: 
    name: docker-compose
    state: present

- name: Create root directory
  file:
    path: "{{ image_root_dir }}"
    state: directory

- name: Copy docker-compose
  template:
    dest: "{{ image_root_dir }}/docker-compose.yml"
    src: "{{ dockercompose_template }}"
  register: dockerfile

- name: create context directories
  file:
    dest: "{{ item.dest | dirname }}"
    owner: "{{ item.dir_owner|default(omit) }}"
    group: "{{ item.dir_group|default(omit) }}"
    mode: "{{ item.dir_mode | default(omit) }}"
    recurse: true
    state: directory
  with_items: "{{ context_dirs }}"

- name: Copy context files
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  with_items: "{{ context_files }}"
  register: context

- name: Install git
  package: 
    name: git
    state: present
  when: dockercompose_git_repositories is defined and ( dockercompose_git_repositories | length ) > 0

- name: Update git repository source code
  git: 
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    force: yes
    version: "{{ item.version | default(omit) }}"
    accept_hostkey: yes
  with_items: "{{ dockercompose_git_repositories }}"
  when: dockercompose_git_repositories is defined
  register: dockercompose_git_repositories_out

- name: Stop docker containers and remove its volumes
  docker_service:
    project_src: "{{ image_root_dir }}"
    state: absent
    remove_volumes: true
    remove_orphans: true
  when: (dockercompose_force_restart | default(false)) or dockerfile.changed or context.changed or dockercompose_git_repositories_out.changed

- name: Start docker containers
  docker_service:
    project_src: "{{ image_root_dir }}"
    restarted: true
    pull: true # upgrade images prior to starting the application
    recreate: always
  when: (dockercompose_force_restart | default(false)) or dockerfile.changed or context.changed or dockercompose_git_repositories_out.changed
