---
- name: Create aspects-nau folder
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Create the aspects-nau folder
      file:
        path: "{{ openedx_tutor_base_folder }}"
        state: directory
        mode: 0755

- name: Generate config.yml file from template
  template:
    src: templates/config.yml
    dest: "{{ openedx_tutor_base_folder }}/config.yml"
    mode: 0644

- name: Copy script.sh to remote server
  template:
    src: templates/script.sh
    dest: "{{ openedx_tutor_base_folder }}/script.sh"
    mode: 0755

- name: Execute script.sh
  shell: "{{ openedx_tutor_base_folder }}/script.sh"
