---
- name: Copy script.sh to remote server
  template:
    src: templates/script.sh
    dest: /path/to/remote/script.sh
    mode: 0755

- name: Execute script.sh
  shell: /path/to/remote/script.sh

  # create a new file not using in line

- name: Generate config.yml file from template
  template:
    src: templates/config.yml.j2
    dest: /path/to/aspects-nau/config.yml
    mode: 0644
  vars:
    MYSQL_HOST: "<MYSQL_HOST>"
    MYSQL_ROOT_PASSWORD: "<MYSQL_ROOT_PASSWORD>"
    MYSQL_ROOT_USERNAME: "<MYSQL_ROOT_USERNAME>"
    RUN_MYSQL: "{{ false }}"
    RUN_MONGODB: "{{ false }}"
    RUN_ELASTICSEARCH: "{{ false }}"


# REMOVE MYSQL COMMANDS AND ADD TO README
- name: Grant privileges to openedx user
  mysql_user:
    name: openedx
    host: "<MYSQL_HOST>"
    password: "<OPENEDX_MYSQL_PASSWORD>"
    priv: "*.*:ALL,GRANT"
    state: present
  become: true

- name: Flush privileges
  command: mysql -h <MYSQL_HOST> -u root -p<MYSQL_ROOT_PASSWORD> -e "FLUSH PRIVILEGES;"
  become: true