---

- name: Install prerequisites
  apt:
    name: "{{ docker_prerequisites }}"
    state: present

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Ensure group docker exists
  group:
    name: docker
    state: present
  notify: Restart docker

- name: adding existing user '{{ ansible_user_id }}' to group docker
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: yes
  notify: Restart docker

- name: Update apt cache
  apt: 
    update_cache: yes

- name: Install Docker
  apt: 
    name: docker-ce
  notify: Restart docker

- name: Install pip module docker-py
  pip:
    name: docker-py
    state: present
  notify: Restart docker

- name: Configure docker daemon
  template:
    dest: /etc/docker/daemon.json
    src: daemon.json.j2
  when: docker_daemon_configurations_dict | length > 0
  notify: Restart docker

- name: Delete docker daemon configuration
  file:
    state: absent
    path: /etc/docker/daemon.json
  when: docker_daemon_configurations_dict | length == 0
  notify: Restart docker

# - name: Prune containers, images, networks, volumes and cache that isn't currently in use by at least one docker container
#   docker_prune:
#     containers: yes
#     images: yes
#     networks: yes
#     volumes: yes
#     builder_cache: yes
