---
image_root_dir: "/home/ubuntu/docker-image"

# Optional parameter
#docker_compose_template: "docker-compose.yml.j2"

docker_compose_folders: "{{ docker_compose_files + docker_compose_templates + docker_compose_git_repositories }}"
docker_compose_files: []
docker_compose_templates: []
docker_compose_git_repositories: []
