---
- name: Install snmpd
  package:
    name: "{{ package_to_install }}"
    state: present
  loop:
    - snmpd
    - snmp
    - snmp-mibs-downloader
  loop_control:
    loop_var: package_to_install
  tags: 
    - snmpd
    - snmp

- name: Configure snmpd
  template: 
    src: templates/snmpd.conf.j2 
    dest: /etc/snmp/snmpd.conf
    backup: yes
  notify: restart snmpd
  tags: 
    - snmpd
    - snmp

- name: Start Service snmpd
  service: 
    name: snmpd 
    state: started 
    enabled: yes
  tags: 
    - snmpd
    - snmp
