---

- name: Make sure we can use htpasswd module for python2
  apt:
    pkg: python-passlib
    state: present
  when: basic_authentication_users is defined and ( basic_authentication_users | length > 0 ) and ( ansible_distribution == 'Ubuntu' and ansible_distribution_major_version <= '20' )

- name: Make sure we can use htpasswd module for python3
  apt:
    pkg: python3-passlib
    state: present
  when: basic_authentication_users is defined and ( basic_authentication_users | length > 0 ) and ( ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '20' )

- name: Create folders
  file:
    dest: "{{ item.path | dirname }}"
    owner: "{{ item.dir_owner|default(omit) }}"
    group: "{{ item.dir_group|default(omit) }}"
    mode: "{{ item.dir_mode | default(omit) }}"
    recurse: true
    state: directory
  when: item.path is defined
  with_items: "{{ basic_authentication_users | default([]) }}"

- name: Write out htpasswd file
  htpasswd:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    path: "{{ item.path }}"
    state: "{{ item.state | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode   | default(omit) }}"
  when: item.name is defined
  with_items: "{{ basic_authentication_users | default([]) }}"
